tests: subsys: mgmt: Fix warning of `size_t` formatting with `%.*s`
This addresses the following warning building with `CONFIG_64BIT=y`:

    error: field precision specifier '.*' expects argument of type 'int',
    but argument X has type 'size_t' {aka 'long unsigned int'}

(cherry picked from commit 1dd6d0db6785626b143d53e559d708725075ac9c)

Original-Original-Signed-off-by: Chen Xingyu <hi@xingrz.me>
Original-GitOrigin-RevId: 1dd6d0db6785626b143d53e559d708725075ac9c
Original-Cr-Build-Id: 8730286630880259329
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8730286630880259329
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I9c5b1bab890c2f0291ab0e500336703f54fb29c0
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6045628
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: 9c3fd36a85c6ffe6e79bc583d0b5a2461125e522
Cr-Build-Id: 8692911841416468593
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692911841416468593
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Idd8e303d97d0be6c0674d5cb3a7bfa4277dcd7fd
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7448350
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>