drivers/timer: Fix build error when run by twister
Fix undefined reference to z_sys_timer_irq_for_test

(cherry picked from commit a75d6a40b6fd3aea2620eb82c684876339926b1e)

Original-Original-Signed-off-by: Andrew Perepech <andrew.perepech@mediatek.com>
Original-GitOrigin-RevId: a75d6a40b6fd3aea2620eb82c684876339926b1e
Original-Cr-Build-Id: 8702282817499087745
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8702282817499087745
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Ice4035db29d859b1e5c08a9211435dc909dea8ba
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7001243
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Tested-by: Keith Short <keithshort@chromium.org>
Original-Commit-Queue: Keith Short <keithshort@chromium.org>
Original-Reviewed-by: Keith Short <keithshort@chromium.org>
GitOrigin-RevId: debd6352086e6dabc3a8508e5736f2acc37fca2e
Cr-Build-Id: 8692687278159146161
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692687278159146161
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I2ecae0795bdff4ab5bd58a462677bb66e2508745
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7474865
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>