meson: Add missing long-long option in conf_data.set for tinystdio
Seems like adding the 'long-long' option to the conf_data.set()
options for 'tinystdio' was accidentally missed. This leads
'_FORMAT_DEFAULT_LONG_LONG' not being set when using the
'format-default=long-long' option, which ultimately leads to the
'vfprintf' etc functions not being registered properly:

    picolibc/newlib/libc/tinystdio/printf.c:41: \
        undefined reference to `vfprintf'

Fix this by adding in the missing entry for the 'long-long' variant.

(cherry picked from commit 4b2b54d03bd300419ac9f8b4e19d5d3b1c7ff957)

Original-Original-Fixes: ca70b2a7ad8b ("libc/tinystdio: Add 'long-long' printf/scanf variants")
Original-Original-Signed-off-by: Louis Peens <louis.peens@corigine.com>
Original-GitOrigin-RevId: 4b2b54d03bd300419ac9f8b4e19d5d3b1c7ff957
Original-Cr-Build-Id: 8723641049794645873
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8723641049794645873
Original-Copybot-Job-Name: zephyr-picolibc-copybot-downstream
Original-Change-Id: I9bcf754aafba2b99b8eae5a078ae9fc5f03c34b6
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/picolibc/+/6241206
Original-Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: 5e01a8058f7ad992a6c3e22be98db7c8783bd1b2
Cr-Build-Id: 8694292306543039489
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694292306543039489
Copybot-Job-Name: zephyr-project-picolibc-copybot-downstream
Change-Id: I25306b899db6c541e2822116735b5c17fc27a70e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7346479
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>