drivers: mdio: nxp_enet: Fix "expected statement" clangsa error
clangsa reports the error

mdio_nxp_enet.c:245:10: error: label at end of compound statement:
expected statement

(cherry picked from commit b4a059df75ab6c84f66c05bf9c2feb89c60d228e)

Original-Original-Signed-off-by: Pieter De Gendt <pieter.degendt@basalte.be>
Original-GitOrigin-RevId: b4a059df75ab6c84f66c05bf9c2feb89c60d228e
Original-Change-Id: I38b06464536ee598a40f1e48d10e3fd19705583b
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5180710
Original-Tested-by: Tristan Honscheid <honscheid@google.com>
Original-Reviewed-by: Tristan Honscheid <honscheid@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: Tristan Honscheid <honscheid@google.com>
GitOrigin-RevId: b31dcd4abd9a1f1905905709fb75da2848e1b920
Cr-Build-Id: 8693095069434521713
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693095069434521713
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I2a6fbb81488b52fdecc1d6ae802775f6bd9e800e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7429888
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>