bluetooth: classic: shell: mitigate label followed by declaration
A recent change triggered a warning in LLVM that was promoted to error
when run with twister.

```shell
goep.c:102:3: error: label followed by a declaration is a C23 extension
  [-Werror,-Wc23-extensions]
  102 |                 int err;
```

Add a scope to the switch case so that the declaration has proper scope.

(cherry picked from commit 62f62dbb0bdedefb9dd4a6fef7da7f91bcf7b298)

Original-Original-Signed-off-by: Chris Friedt <cfriedt@tenstorrent.com>
Original-GitOrigin-RevId: 62f62dbb0bdedefb9dd4a6fef7da7f91bcf7b298
Original-Cr-Build-Id: 8707016510567822897
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8707016510567822897
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Ia8284cb598a04e47833b3298e727b79d2d3defcd
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6833026
Original-Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
GitOrigin-RevId: a24d8ad629af4ef18bc7ef4565755e7a0b484790
Cr-Build-Id: 8692727672995070433
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692727672995070433
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I9cfc0179492a9bd3e09f7d8a4a06c526b4c90bfd
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7469897
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>