drivers: display: rm67162: avoid uninitialized variable
Warning as error was:

.../drivers/display/display_rm67162.c: In function ‘rm67162_write_fb’:
.../drivers/display/display_rm67162.c:383:9: error: ‘wlen’ may be used
          uninitialized in this function [-Werror=maybe-uninitialized]
  383 |  return wlen;
      |         ^~~~

(cherry picked from commit 8bf8eeb3383d5e2c6eb3495bd3886ce851d3dd70)

Original-Original-cc1: all warnings being treated as errors
Original-Original-Signed-off-by: Stephan Linz <linz@li-pro.net>
Original-GitOrigin-RevId: 8bf8eeb3383d5e2c6eb3495bd3886ce851d3dd70
Original-Cr-Build-Id: 8692022711654242305
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692022711654242305
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I439b1c8830bcea6ef3503afac049c0765a349eba
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7508426
Original-Reviewed-by: Dawid Niedźwiecki <dawidn@google.com>
Original-Reviewed-by: Jon Murphy <jpmurphy@google.com>
Original-Tested-by: Dawid Niedźwiecki <dawidn@google.com>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Commit-Queue: Dawid Niedźwiecki <dawidn@google.com>
GitOrigin-RevId: f2c1a2f1046859b1ec0b05ee3ade53d46bdd1e9e
Change-Id: Ifc6341dda36b9c766c2e568bc292936e19389782
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7514075
Tested-by: Jon Murphy <jpmurphy@google.com>
Reviewed-by: Brett Brotherton <bbrotherton@google.com>