samples: net: midi2: Fix compiler warning
When building with clang we get the following warning when building the
sample.net.midi2.host_auth_user test:

samples/net/midi2/src/main.c:122:54: error: initializer element is not a
compile-time constant
  122 | NETMIDI2_EP_DEFINE_WITH_USERS(midi_server, ump_ep_dt.name, NULL, 0,
      |                                            ~~~~~~~~~~^~~~
include/zephyr/net/midi2.h:99:12: note: expanded from macro
'NETMIDI2_EP_DEFINE_WITH_USERS'
   99 |                 .name = (_ep_name), \
      |                          ^~~~~~~~

Instead of using ump_ep_dt.name for initialization, we use the
equivalent expression that UMP_ENDPOINT_DT_SPEC_GET(DT_NODELABEL(midi2))
initializes the ".name" member with.

(cherry picked from commit f9664d51c31b2dffaa37c78e4f85db72a77ff232)

Original-Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Original-GitOrigin-RevId: f9664d51c31b2dffaa37c78e4f85db72a77ff232
Original-Cr-Build-Id: 8692045360469606417
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692045360469606417
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I33e94b90507e9db7776515174d83d9c01cb12d45
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7505893
Original-Reviewed-by: Jon Murphy <jpmurphy@google.com>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Reviewed-by: Dawid Niedźwiecki <dawidn@google.com>
Original-Tested-by: Dawid Niedźwiecki <dawidn@google.com>
Original-Commit-Queue: Dawid Niedźwiecki <dawidn@google.com>
GitOrigin-RevId: 2c4071a089773e402d5e196d9641bd0206163103
Change-Id: Ic8ed15a463a27b0dde4c64352abe276e26280b68
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7514012
Tested-by: Jon Murphy <jpmurphy@google.com>
Reviewed-by: Brett Brotherton <bbrotherton@google.com>