scripts: kconfig: gnuconfig: Ignore loc
The commit 125d0daaa17aa added 'loc' to the sym.ranges tuples and fixed
kconfiglib.py but guiconfig.py is left untouched. This make menuconfig to
die with:

  Exception in Tkinter callback
  Traceback (most recent call last):
    File "/usr/lib/python3.13/tkinter/__init__.py", line 2077, in __call__
      return self.func(*args)
             ~~~~~~~~~^^^^^^^
    File ".../scripts/kconfig/guiconfig.py", line 917, in _tree_double_click
      return _tree_enter(event)
    File ".../scripts/kconfig/guiconfig.py", line 942, in _tree_enter
      _change_node(node, tree.winfo_toplevel())
      ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File ".../scripts/kconfig/guiconfig.py", line 1125, in _change_node
      s = _set_val_dialog(node, parent)
    File ".../scripts/kconfig/guiconfig.py", line 1219, in _set_val_dialog
      range_info = _range_info(sym)
    File ".../scripts/kconfig/guiconfig.py", line 1339, in _range_info
      for low, high, cond in sym.ranges:
          ^^^^^^^^^^^^^^^
  ValueError: too many values to unpack (expected 3)

This commit ignores the last element in the tuples.

(cherry picked from commit 6d6508ae12e5a5e42b6c693663e1e025e462dcfb)

Original-Original-Signed-off-by: Yasushi SHOJI <yashi@spacecubics.com>
Original-GitOrigin-RevId: 6d6508ae12e5a5e42b6c693663e1e025e462dcfb
Original-Cr-Build-Id: 8698455093734075649
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8698455093734075649
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Idf7655bd4308b9af634b337b42ada44436e546b5
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7142148
Original-Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
GitOrigin-RevId: e32b3702c9bd00ef838152db87726aa60fbecb46
Cr-Build-Id: 8692647051261749617
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692647051261749617
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ib3637f5fae9b38a2718f1e37e2bae91009e88de0
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7479673
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>