tests: interrupt: Fix armclang compiler warning
When building this test with the armclang compiler we get the following

tests/kernel/interrupt/src/dynamic_isr.c
tests/kernel/interrupt/src/dynamic_isr.c:23:32: error: 'used' attribute
ignored on a non-definition declaration [-Werror,-Wignored-attributes]

extern struct _isr_table_entry __sw_isr_table _sw_isr_table[];
                               ^
There is no need to add the __sw_isr_table on the extern, so remove it
to address the warning.

(cherry picked from commit 99fee43f077b69cb735f81c843a9ea2d434a5e0f)

Original-warning:
Original-Original-Signed-off-by: Kumar Gala <kumar.gala@intel.com>
Original-GitOrigin-RevId: 99fee43f077b69cb735f81c843a9ea2d434a5e0f
Original-Change-Id: I9590f9785314a71d6c00f93f29daba4817dc4853
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4414157
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Reviewed-by: Yuval Peress <peress@google.com>
Original-Commit-Queue: Yuval Peress <peress@google.com>
Original-Tested-by: Yuval Peress <peress@google.com>
GitOrigin-RevId: 426b48dca1f1ea518e347e23d2a48693169bfc83
Cr-Build-Id: 8693296959394875345
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693296959394875345
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I45a7e06f68e0be1ea5b6d0830a7cc163ecfed777
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7412320
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>