modules: CMSIS_6: Switch to CMSIS_6 for Cortex-M
What is the change?
Switch to module CMSIS_6 for Cortex-M while continuing to use
cmsis module (version 5.9.0) for Cortex-A/R.

Why do we need this change?

The current cmsis module consists of:
- Cortex-M support from upstream cmsis 5.9.0
- Cortex-A/R support which was not upstreamed to CMSIS

Upstream cmsis 5.9 was deprecated so we should be using CMSIS_6 however,
it seems due to lack of Cortex-A/R support in upstream and other reasons,
this was pushed back.

While upstreaming Cortex-A/R support to CMSIS_6 could take its time,
this shouldn't stop Cortex-M to start using CMSIS_6.

Also, if we do not use CMSIS_6 for Cortex-M then using the
newer GCC 14.2 toolchain will return below compiler error:
```
zephyrproject/modules/hal/cmsis/CMSIS/Core/Include/core_cm85.h:4406:10:
fatal error: pac_armv81.h: No such file or directory
 4406 | #include "pac_armv81.h"
```
Using CMSIS_6 for Cortex-M will fix this.

(cherry picked from commit f726cb5123eda12feb8746e3acb34a1f7d7b0340)

Original-Original-Signed-off-by: Sudan Landge <sudan.landge@arm.com>
Original-GitOrigin-RevId: f726cb5123eda12feb8746e3acb34a1f7d7b0340
Original-Cr-Build-Id: 8714898446203671153
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8714898446203671153
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Ic79ef32286452daa6e29b72cfb10b33110968d21
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6546342
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
GitOrigin-RevId: 61e9e574293f4e559ebfb23abdd84608daa1b66f
Cr-Build-Id: 8692792910433217201
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692792910433217201
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I13d22b68b31f3ef4b340fab813a4e6f149e02831
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7463004
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>