subsys/logging: Fix xtensa simcall assembly
This construction was causing errors with recent gccs.  If you look
carefully, it's generating the sequence:

  simcall
  mov a2, a2
  mov a3, a3

...which is nonsensical.  And now gcc is complaining about it with:

    subsys/logging/log_backend_xtensa_sim.c:44:2:
        error: invalid hard register usage between output operands

Just emit a single simcall instruction and let the assembly
constraints do their job.

Original-Signed-off-by: Andy Ross <andrew.j.ross@intel.com>
GitOrigin-RevId: 9ec17d6556ba6063eb02c35b27efccdbd96a179d
Cr-Build-Id: 8694098334402396097
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694098334402396097
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Idce107e5a2f84ffab2e7a163882a598cf5ce7ecd
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7356579
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>