Devicetree: edtlib: fix possible AttributeError in Property.description
Attempting to access the property Property.description
when Property.spec.description is None would raise

Known properties that may not have a description
(Property.spec.description is None):
- 'compatible' for nodes such as / /soc /soc/timer@e000e010 /leds /pwmleds
- 'reg'        for nodes such as /soc/timer@e000e010
- 'status'     for nodes such as /soc/timer@e000e010
- 'gpios'      for nodes such as /leds/led_0 /buttons/button_0
- 'pwms'       for nodes such as /pwmleds/pwm_led_0

This patch checks the PropertySpec.description attribute before calling
strip(): will return None, and not raise AttributeError.

(cherry picked from commit 230c80e0009f23edd5f0fc477c80df760a3d5590)

Original-Original-AttributeError: 'NoneType' object has no attribute 'strip'.
Original-Original-Signed-off-by: Chris Duf <chris@openmarl.org>
Original-Original-Co-authored-by: Gerard Marull-Paretas <gerard@teslabs.com>
Original-GitOrigin-RevId: 230c80e0009f23edd5f0fc477c80df760a3d5590
Original-Change-Id: I1ae46a54dc7ea268d5df85590ff01646239c098f
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3952474
Original-Tested-by: Keith Short <keithshort@chromium.org>
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Reviewed-by: Keith Short <keithshort@chromium.org>
Original-Commit-Queue: Keith Short <keithshort@chromium.org>
GitOrigin-RevId: 426c06f72e8a3ffb6c1a70348fa4590594e62939
Cr-Build-Id: 8693433802299994337
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693433802299994337
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ie7cf75d113ca3ee99077a110b23677ebf3743cfc
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7402397
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>