drivers: dai: ssp: remove unused variables
Fix compiler warnings
/zep_workspace/zephyr/drivers/dai/intel/ssp/ssp.c:2079:18: error: \
unused variable 'ssrsa' [-Werror=unused-variable]
 2079 |         uint32_t ssrsa = 0;
      |                  ^~~~~
/zep_workspace/zephyr/drivers/dai/intel/ssp/ssp.c:2078:18: error: \
unused variable 'sstsa' [-Werror=unused-variable]
 2078 |         uint32_t sstsa = 0;
      |                  ^~~~~

(cherry picked from commit 6f1fc6e96c60cbbfacabad9685f4d034f4bed5c1)

Original-Original-Signed-off-by: Guennadi Liakhovetski <guennadi.liakhovetski@linux.intel.com>
Original-GitOrigin-RevId: 6f1fc6e96c60cbbfacabad9685f4d034f4bed5c1
Original-Cr-Build-Id: 8728129377422644657
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8728129377422644657
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I222f82d95dc53e525e57d4710d2ce262ab796f8a
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6110923
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: Dawid Niedźwiecki <dawidn@google.com>
Original-Tested-by: Dawid Niedźwiecki <dawidn@google.com>
Original-Reviewed-by: Dawid Niedźwiecki <dawidn@google.com>
GitOrigin-RevId: 5bda5155356793aef76f012e488b3c545cc523c0
Cr-Build-Id: 8692890494136518161
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692890494136518161
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I56891626955651c9aa96cbd4e90b8ce74879bae4
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7450687
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>