kconfig: Fail in CI if Kconfig files reference undefined symbols
Add a helper module scripts/ci/list_undef_kconfig_refs.py that searches
the entire Kconfig tree and reports any references to undefined Kconfig
symbols. Use it to add a new check to scripts/ci/check-compliance.py.

Also allow list_undef_kconfig_refs.py to be run standalone.

Example error:

  Error: Found references to undefined Kconfig symbols:

  BAR
  ===

  - Referenced at Kconfig:12:

  config FOO
        bool
        depends on BAR

  - Referenced at Kconfig:16:

  menu "menu"
        depends on BAR

Original-Signed-off-by: Ulf Magnusson <Ulf.Magnusson@nordicsemi.no>
GitOrigin-RevId: 5bfc7ff2753c9b4c8eb29adb26c77605c5eb4836
Cr-Build-Id: 8694541799953182209
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694541799953182209
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ifeff514fd0b2559e61c15e0701fcf6e504273494
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7326708
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>