drivers: crypto_mbedtls_shim: Fix build with Clang/LLVM
drivers/crypto/crypto_mbedtls_shim.c:310:3: error: label followed by a
declaration is a C23 extension [-Werror,-Wc23-extensions]
                 uint16_t tag_len = ctx->mode_params.ccm_info.tag_len;
                 ^

(cherry picked from commit 69946a1253db1326a06e73303d79b8ec652a90f4)

Original-Original-Signed-off-by: Johan Hedberg <johan.hedberg@silabs.com>
Original-GitOrigin-RevId: 69946a1253db1326a06e73303d79b8ec652a90f4
Original-Cr-Build-Id: 8696326068362242273
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8696326068362242273
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Ic0ba30b81c531ccddb9b18a6ae3d4b929d8a2c0f
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7231820
Original-Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
GitOrigin-RevId: cb6a054ac5e5a83f709ef8b41313a594b8e21d40
Cr-Build-Id: 8692625244129440977
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692625244129440977
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I4c73ef38a98aa9100d80d511886a7ac5e6a9a079
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7482607
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>