scripts: west_commands: patch: treat all subprocess output as text
Pass 'encoding="utf-8"' to all 'subprocess.run()' calls.
This treats the captured stdout and stderr streams as text rather than
byte sequences.

Example without this patch:
west patch apply --roll-back
FATAL ERROR: failed to apply patch libcsp/test.patch

Example with this patch:
west patch apply --roll-back

FATAL ERROR: failed to apply patch libcsp/test.patch

(cherry picked from commit 039013f8ef39fc818d6fe4417f92b04005a35368)

Original-Original-ERROR: b'error: patch failed: examples/csp_server_client.py:32\n
Original-Original-error: examples/csp_server_client.py: patch does not apply\n'
Original-Original-ERROR: error: patch failed: examples/csp_server_client.py:32
Original-Original-error: examples/csp_server_client.py: patch does not apply
Original-Original-Signed-off-by: Mirai SHINJO <oss@mshinjo.com>
Original-GitOrigin-RevId: 039013f8ef39fc818d6fe4417f92b04005a35368
Original-Cr-Build-Id: 8697956813069601489
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8697956813069601489
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I1686cabdc38232ac53e1d9dea82f92ab6ca0df15
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7159641
Original-Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
GitOrigin-RevId: 6fd9b2e688456a3e3c58ac06681decbc5cf1ed70
Cr-Build-Id: 8692642471503419777
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692642471503419777
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I8b4cf4349fb03617b3a6f59963a6bdb798b74b08
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7480345
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>