libgloss: Remove duplicate definition of environ
Environ is defined in libgloss and libc:
 - libgloss/or1k/syscalls.c
 - libc/stdlib/environ.c

When linking we sometimes get errors:
or1k-elf-g++ test.o -mnewlib -mboard=or1ksim -lm -o  test
/opt/shorne/software/or1k/lib/gcc/or1k-elf/5.3.0/../../../../or1k-elf/lib/libor1k.a(syscalls.o):(.data+0x0):
multiple definition of `environ'
/opt/shorne/software/or1k/lib/gcc/or1k-elf/5.3.0/../../../../or1k-elf/lib/libc.a(lib_a-environ.o):(.data+0x0):
first defined here

This doesnt happen after the fix. Basic things build fine too.

Original-collect2: error: ld returned 1 exit status
GitOrigin-RevId: 135c0c83680d5d39bfe326e497ace47c0bff1650
Cr-Build-Id: 8694335555632936993
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694335555632936993
Copybot-Job-Name: zephyr-project-picolibc-copybot-downstream
Change-Id: I79be89ed68d1a7eeb262f47c6aa7eef828cd24e7
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7340294
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>