ext/hal/st/stm32cube/stm32l1xx: rename SVC_IRQn -> SVCall_IRQn
SVCall_IRQn is used as enum value for SV Call Interrupt for Cortex-M
based SoCs for which CPU_CORTEX_M_HAS_BASEPRI=y. However stm32cube
for stm32l1xx uses SVC_IRQn enum value for this purpose.
This leads to this error:

  arch/arm/include/cortex_m/exc.h:101:19: error: 'SVCall_IRQn'
    undeclared (first use in this function); did you mean 'SVC_IRQn'?

    NVIC_SetPriority(SVCall_IRQn, _EXC_SVC_PRIO);
                     ^~~~~~~~~~~
                     SVC_IRQn

fixed in 9f8260457b86 ('ext: hal: st: stm32cube: Add HAL for
the STM32L1x series').

Original-NB: ext/hal/st/stm32cube/stm32l1xx/soc/stm32l151xb.h file was already
Original-Signed-off-by: Antony Pavlov <antonynpavlov@gmail.com>
GitOrigin-RevId: a659ade859a847eb9a60c4f7f292072600c6eb23
Cr-Build-Id: 8697705723722832193
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8697705723722832193
Copybot-Job-Name: zephyr-project-stm32-copybot-downstream
Change-Id: I533cd82b6ef7a690ef5171d8b35501b86c8d2f16
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7174629
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>