tests: bsim: testlib: Fix compilation error
Fixes compilation error seen if CONFIG_BT_EATT is unset

testlib/src/att_read.c:179:73: error: expected expression before ‘,’ token
179 |               IF_ENABLED(CONFIG_BT_EATT, (.chan_opt = bearer)),
    |                                                               ^

(cherry picked from commit f0715fcbb3ebaacee805cb1431a6c8460f1e67b4)

Original-Original-Signed-off-by: Mariusz Skamra <mariusz.skamra@codecoup.pl>
Original-GitOrigin-RevId: f0715fcbb3ebaacee805cb1431a6c8460f1e67b4
Original-Change-Id: I9cb9a8aeba229e0ca1e3c1d1dd42f269a86e0da7
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5023933
Original-Reviewed-by: Keith Short <keithshort@chromium.org>
Original-Commit-Queue: Keith Short <keithshort@chromium.org>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Tested-by: Keith Short <keithshort@chromium.org>
GitOrigin-RevId: 4769a334527737538892ba5777d576c37db124b0
Cr-Build-Id: 8693123603935546065
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693123603935546065
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Iabf228a286e50563445637764b705a6e10a87cb7
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7426853
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>