mgmt/mcumgr: add missing designator to ZCBOR_MAP_DECODE_KEY_DECODER
Add missing `.key` designator.

This also fixes a compile error:
> error: either all initializer clauses should be designated or none of
them should be

(cherry picked from commit 6e7268d21bcec208a82bd014cb0281b9adc1b9bf)

Original-Original-Signed-off-by: Jeppe Odgaard <jeppe.odgaard@prevas.dk>
Original-GitOrigin-RevId: 6e7268d21bcec208a82bd014cb0281b9adc1b9bf
Original-Cr-Build-Id: 8703279383919101409
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8703279383919101409
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I6f6988a2b5337c7bcbdc9d4c9d9087cffb7a9b7c
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6969599
Original-Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Commit-Queue: Jeremy Bettis <jbettis@chromium.org>
Original-Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
GitOrigin-RevId: cdaaaaba8d8b2c094ae7aee0e784270c9b1b6917
Cr-Build-Id: 8692694726716210273
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692694726716210273
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I1984bd069bc4031aacb4baafa734b6d71c501539
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7473408
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>