Restore original ifdef in limits.h for the include_next of system's limits.h
Commit 2f5f8439bd61e93e0f42d8009324d8c5227153c1 made changes to the
preprocessor guard that gated the include_next directive for limits.h

Currently the guard looks something like this:

```
ifdef __GNUC__
 include_next<limits.h>
endif
```

The original guard, on the other hand, also checked for _GCC_LIMITS_H_.
This extra condition is necessary to build with Clang. This error
message is shown:

> fatal error: 'limits.h' file not found

Because include_next is run when it shouldn't.

(cherry picked from commit 59843b2e121129ad5fafaa615dbfa4e1c472fd48)

Original-GitOrigin-RevId: 59843b2e121129ad5fafaa615dbfa4e1c472fd48
Original-Cr-Build-Id: 8731843854058218129
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8731843854058218129
Original-Copybot-Job-Name: zephyr-picolibc-copybot-downstream
Original-Change-Id: I739a3881c527fbc675ecda87079b625a96c7d8c0
GitOrigin-RevId: 98963946c0ddad1af1825a27c26d86ad7011957f
Cr-Build-Id: 8694293527482652817
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694293527482652817
Copybot-Job-Name: zephyr-project-picolibc-copybot-downstream
Change-Id: Iec9394d1e0cb31984c0a95a8636a24df6e5b4f71
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7346334
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>