Bluetooth: Mesh: Fix build warning with gcc 13
gcc 13 thinks  max_adv_duration may be used unitialized
and warns accordingly (see below)
It seems the reason is the goto, which confuses it.
In any case, pacifying this warning is trivial,
so let's just do so.

The warning:
```
In function ‘gatt_proxy_advertise’,
inlined from ‘bt_mesh_proxy_adv_start’ at
subsys/bluetooth/mesh/proxy_srv.c:1214:9:
subsys/bluetooth/mesh/proxy_srv.c:842:44: error: ‘max_adv_duration’ may
be used uninitialized [-Werror=maybe-uninitialized]
subsys/bluetooth/mesh/proxy_srv.c: In function ‘bt_mesh_proxy_adv_start’
zephyr/subsys/bluetooth/mesh/proxy_srv.c:786:17: note:
‘max_adv_duration’ was declared here
  786 |         int32_t max_adv_duration;
      |                 ^~~~~~~~~~~~~~~~
```

(cherry picked from commit e3da5c3d390f2c2a9c0f470df7456947ad188c30)

Original-Original-Signed-off-by: Alberto Escolar Piedras <alberto.escolar.piedras@nordicsemi.no>
Original-GitOrigin-RevId: e3da5c3d390f2c2a9c0f470df7456947ad188c30
Original-Cr-Build-Id: 8739544594786469985
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8739544594786469985
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I5718fd57c8d73b05fef761289c5942003e3f610a
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5788472
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Owners-Override: Jonathon Murphy <jpmurphy@google.com>
Original-Commit-Queue: Dawid Niedźwiecki <dawidn@google.com>
Original-Tested-by: Dawid Niedźwiecki <dawidn@google.com>
Original-Reviewed-by: Jonathon Murphy <jpmurphy@google.com>
Original-Reviewed-by: Dawid Niedźwiecki <dawidn@google.com>
GitOrigin-RevId: aa163b5f8670e3ed1f8ce80bc3c68fd3af94617c
Cr-Build-Id: 8692976023217314529
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692976023217314529
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I618d9d31e3d487914c5b7f6c1c90862ec33e31ab
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7441721
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>