net: websocket: fix undefined reference
Fix undefined reference to MSG_DONTWAIT while building websocket client.

(cherry picked from commit 4c16ec1fba56c5631fb0ab19583a8a30d7ded529)

Original-Original-Signed-off-by: Joel Guittet <joelguittet@gmail.com>
Original-GitOrigin-RevId: 4c16ec1fba56c5631fb0ab19583a8a30d7ded529
Original-Cr-Build-Id: 8739001010820476625
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8739001010820476625
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I0c760987d5f8cec33e87f78de1c37eaf1ed33d80
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5803472
Original-Reviewed-by: Eric Yilun Lin <yllin@google.com>
Original-Tested-by: Eric Yilun Lin <yllin@google.com>
Original-Commit-Queue: Eric Yilun Lin <yllin@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: 07b5cbfdaf25f2cd12d947a0b21f805b2eda3e61
Cr-Build-Id: 8692970579647087041
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692970579647087041
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ia5b650653c0616dd5d2ecb58fb5838034c931d59
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7442316
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>