logging: Workaround build warning with clang
when building with clang we get the following warning:

log_core.c:358:40: error: use of logical '&&' with constant operand
[-Werror,-Wconstant-logical-operand]

This is because we are mix a constant IS_ENABLED(CONFIG_LOG_IMMEDIATE)
with non-constants.

Split out the check into its own statement to workaround the warning.

Original-Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
GitOrigin-RevId: cb3fe3cc4673946bea26cbf7ac4762e851b711aa
Cr-Build-Id: 8694300957878353473
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694300957878353473
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I22a638ee6cb468d3238625513aa1f27f5a547abc
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7344743
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>