tests: mcumgr: Re-enable clang warning by using variables
When removing TOOLCHAIN_DISABLE_CLANG_WARNING, building the
settings.mgmt test with clang fails with:

tests/subsys/mgmt/mcumgr/settings_mgmt/src/main.c:87:22: error:
variable 'test_response_read_data_start' is not needed and will not be
emitted [-Werror,-Wunneeded-internal-declaration]
   87 | static const uint8_t test_response_read_data_start[5] = {
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tests/subsys/mgmt/mcumgr/settings_mgmt/src/main.c:91:22: error:
variable 'test_response_read_data_end' is not needed and will not be
emitted [-Werror,-Wunneeded-internal-declaration]
   91 | static const uint8_t test_response_read_data_end[1] = {

Add additional asserts to use these variables in the test.

(cherry picked from commit 2d6aa4739886a923d650cb4403e623d89422aa28)

Original-Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Original-GitOrigin-RevId: 2d6aa4739886a923d650cb4403e623d89422aa28
Original-Cr-Build-Id: 8692022711654242305
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692022711654242305
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I873d9413b9e0614dece2ebaeced2c9b4665b288e
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7508427
Original-Reviewed-by: Jon Murphy <jpmurphy@google.com>
Original-Reviewed-by: Dawid Niedźwiecki <dawidn@google.com>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Commit-Queue: Dawid Niedźwiecki <dawidn@google.com>
Original-Tested-by: Dawid Niedźwiecki <dawidn@google.com>
GitOrigin-RevId: cee5f9bba4f0608ad1327471802ec9ac0fd1c70a
Change-Id: Ieaed408d85f19a93e976ee4774827973eac3359f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7514076
Tested-by: Jon Murphy <jpmurphy@google.com>
Reviewed-by: Brett Brotherton <bbrotherton@google.com>