drivers: gpio: pca95xx: Remove unused functions
Building with clang warns:

drivers/gpio/gpio_pca95xx.c:256:19: error: unused function
'update_input_reg' [-Werror,-Wunused-function]
static inline int update_input_reg(const struct device *dev, uint8_t pin,
                  ^

drivers/gpio/gpio_pca95xx.c:120:12: error: unused function
'read_port_reg' [-Werror,-Wunused-function]
static int read_port_reg(const struct device *dev, uint8_t reg,
           ^             uint8_t pin,

(cherry picked from commit 65b4e594d736258e77770437d66f158eb840d798)

Original-Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Original-GitOrigin-RevId: 65b4e594d736258e77770437d66f158eb840d798
Original-Cr-Build-Id: 8723006874034296081
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8723006874034296081
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Id673cae0fd187a40630ab87cacbab2b7c807148a
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6266721
Original-Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: db022d3a0fda1d7097a697efcbe1408a423883ec
Cr-Build-Id: 8692854981942345489
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692854981942345489
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: If276871e97b247688daef0c124680732fbb94123
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7456300
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>