net: l2: ethernet: Fix unused function warning
Building with clang warns:

subsys/net/l2/ethernet/ethernet.c:178:18: error: unused function
'ethernet_check_ipv4_bcast_addr' [-Werror,-Wunused-function]
enum net_verdict ethernet_check_ipv4_bcast_addr(struct net_pkt *pkt,
                 ^

ethernet_check_ipv4_bcast_addr is called by ethernet_ip_recv, which only
exists when CONFIG_NET_IPV4 or CONFIG_NET_IPV6 is defined.

(cherry picked from commit 9838a03ad752d1f02b6c4f1ba57d4899246572a5)

Original-Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Original-GitOrigin-RevId: 9838a03ad752d1f02b6c4f1ba57d4899246572a5
Original-Cr-Build-Id: 8722350046011102081
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8722350046011102081
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I519e0ddcc3ef9654fe28c685ef7b928a350ad79e
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6290812
Original-Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: fb9b93ef9b9a50ebe2f88be9ccc3da79a44bddea
Cr-Build-Id: 8692849501808077921
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692849501808077921
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I2bea7bf42d9e0f5829230564f0b6695ff6ff8820
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7457092
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>