Bluetooth: host: Fix scan info dangling pointer
Clear pointer to the le_adv_recv() stack frame before returning to the
calling function. This fixes a potential compiler warning newer gcc
versions.

zephyr/subsys/bluetooth/host/scan.c: In function ‘le_adv_recv’:
zephyr/subsys/bluetooth/host/scan.c:463:20: error: storing the address
of local variable ‘id_addr’ in ‘*info.addr’ [-Werror=dangling-pointer=]
  463 |         info->addr = &id_addr;
      |         ~~~~~~~~~~~^~~~~~~~~~
zephyr/subsys/bluetooth/host/scan.c:439:22: note: ‘id_addr’ declared here
  439 |         bt_addr_le_t id_addr;
      |                      ^~~~~~~

Fixes #48459

(cherry picked from commit 7ebaf1b10b9a584e8f9d7529407b495766684bfe)

Original-Original-Signed-off-by: Johan Hedberg <johan.hedberg@intel.com>
Original-GitOrigin-RevId: 7ebaf1b10b9a584e8f9d7529407b495766684bfe
Original-Change-Id: I7289c3940f4a3a09f7ce0a75d2521ea6a5f76980
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3814823
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: d8883043afd2b24062429f20f2be362c57008019
Cr-Build-Id: 8693491704402870897
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693491704402870897
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I2850644c000e63f788868e57d5016b1da3f5fe51
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7398191
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>