net: lib: http_server: Remove unused function
Building with clang warns:

subsys/net/lib/http/http_hpack.c:21:20: error: unused function
'http_hpack_key_is_dynamic' [-Werror,-Wunused-function]
static inline bool http_hpack_key_is_dynamic(uint32_t key)
                   ^

(cherry picked from commit 1f653ae2955af25b59c5a489c7977ada0863d040)

Original-Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Original-GitOrigin-RevId: 1f653ae2955af25b59c5a489c7977ada0863d040
Original-Cr-Build-Id: 8723142769276654049
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8723142769276654049
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I7a15467def655a44bc68862d827f7b3b9e1c90b5
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6257283
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: 6a9b7f629725ba56b1520a5294d6a4a8ed9c65a3
Cr-Build-Id: 8692857091111002929
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692857091111002929
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ida6c864a301865ad52c4180a277e242203c3a180
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7455903
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>