net: ip: Fix compile error due to config dependency
This patch fixes the compile error when CONFIG_NET_PKT_LOG_LEVEL
is LOG_LEVEL_DBG.

> subsys/net/ip/net_shell.c: In function ‘context_info’:
> subsys/net/ip/net_shell.c:2893:106: error: ‘struct net_buf_pool’
> has no member named ‘avail_count’
> subsys/net/ip/net_shell.c:2893:125: error: ‘struct net_buf_pool’
> has no member named ‘name’

In struct net_buf_pool, 'avail_count' and 'name' are depends on
CONFIG_NET_BUF_POOL_USAGE.

Original-Signed-off-by: Tedd Ho-Jeong An <tedd.an@intel.com>
GitOrigin-RevId: 548361c4e298878c1a2b7c50beb3e82704fc3ad4
Cr-Build-Id: 8694506248695669137
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694506248695669137
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I4f47f62844cf80570b7b85b863a44b3f9aee881e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7329672
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>