nxp_adsp: linker: Fix _heap_sentry reference
Add _heap_sentry value to fix build errors for
newlib, like: "undefined reference to `_heap_sentry'"

(cherry picked from commit 9cac089f8c51b3c47b1b42bd0b99766f69b296db)

Original-Original-Signed-off-by: Iuliana Prodan <iuliana.prodan@nxp.com>
Original-GitOrigin-RevId: 9cac089f8c51b3c47b1b42bd0b99766f69b296db
Original-Change-Id: I1ea4419cfeb80d9c434e056eb46a2f3973461a80
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5044059
Original-Commit-Queue: Tristan Honscheid <honscheid@google.com>
Original-Reviewed-by: Tristan Honscheid <honscheid@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Tested-by: Tristan Honscheid <honscheid@google.com>
GitOrigin-RevId: 00140a39d162fd8acb91c90fbefe9b97dba3491a
Cr-Build-Id: 8693117245179368801
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693117245179368801
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I90bf70fdf662ab04848f4cae61a31469fbfdf396
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7427542
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>