cmsis: resolve undefined reference to k_calloc()
When no heap has been configured, osMessageQueueNew() will no
longer include a call to k_calloc() (which needs the heap).
In such a configuration, if osMessageQueueNew() indicates that
the buffer must be allocated, it will fail and return NULL.

Fixes #61196

(cherry picked from commit 467ce8945823b351b97b00aba32aa5d88013b5cf)

Original-Original-Signed-off-by: Peter Mitsis <peter.mitsis@intel.com>
Original-GitOrigin-RevId: 467ce8945823b351b97b00aba32aa5d88013b5cf
Original-Change-Id: Id0128a584c7c5b8eaa08a026e0817950f0c24d9f
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4978791
Original-Commit-Queue: Al Semjonovs <asemjonovs@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Tested-by: Al Semjonovs <asemjonovs@google.com>
Original-Reviewed-by: Al Semjonovs <asemjonovs@google.com>
GitOrigin-RevId: 2d91b45044776712c2e869216abf31ac926e91c1
Cr-Build-Id: 8693132981822070337
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693132981822070337
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Iaa6ff04a6b26494063839b357ffd098e6df01499
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7425718
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>