drivers: display: ls0xx: fix compiler warning
Fix a compiler warning introduced in 0fa2c45037:

/zephyr/drivers/display/ls0xx.c: In function 'ls0xx_init':
/zephyr/drivers/display/ls0xx.c:294:9: error: passing argument 5 of
'k_thread_create' discards 'const' qualifier from pointer target type
[-Werror=discarded-qualifiers]
  294 |         config, NULL, NULL,
      |         ^~~~~~

(cherry picked from commit 824bb337d552828de4394d74c801d26486f05868)

Original-Signed-off-by: Fabio Baltieri <fabio.baltieri@gmail.com>
Original-GitOrigin-RevId: 824bb337d552828de4394d74c801d26486f05868
Original-Change-Id: Ie2baaf95e9321124b7da498273aff5ba5214ccae
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3490966
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Reviewed-by: Aaron Massey <aaronmassey@google.com>
Original-Commit-Queue: Aaron Massey <aaronmassey@google.com>
Original-Tested-by: Aaron Massey <aaronmassey@google.com>
GitOrigin-RevId: da1adf0900c58c57a4a41b06e714d87a770a4447
Cr-Build-Id: 8693623245984189217
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693623245984189217
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I560532b9c11337d41d2eeb58521f3180d345582a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7389077
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>