x86: Fix build when optimizations are disabled
When building without optimizations and with only one core the linker
does not throw away arch_start_cpu and we get an undefined reference to
x86_ap_start

(cherry picked from commit 9f70cd557bf87cd84a9b19196bcc783e0f595416)

Original-Original-Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>
Original-GitOrigin-RevId: 9f70cd557bf87cd84a9b19196bcc783e0f595416
Original-Change-Id: Ib03c2c2c1e19ed3d0cd5268aa1e382636cce5ef0
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5044014
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Tested-by: Tristan Honscheid <honscheid@google.com>
Original-Reviewed-by: Tristan Honscheid <honscheid@google.com>
Original-Commit-Queue: Tristan Honscheid <honscheid@google.com>
GitOrigin-RevId: 91e1ebb034a4ff398f979d67e14e4ea303122309
Cr-Build-Id: 8693119361452865953
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693119361452865953
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: If172ecdb1cfd5a212d517bb7c227f04410250b34
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7427417
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>