Use DnsFree instead of deprecated DnsRecordListFree
The latest version of the mingw headers have been updated to make
DnsRecordListFree an alias of DnsFree when targeting Windows XP or later.
Use DnsFree directly, avoiding the wrapper function.

/home/peter/cross/src/cygwin/winsup/cygwin/libc/minires-os-if.c:289:
undefined reference to `DnsFree'

winsup/cygwin/ChangeLog
autoload.cc: Load DnsFree rather then DnsRecordListFree
libc/minires-os-if.cc (cygwin_query): Use DnsFree rather then DnsRecordListFree

Original-Signed-off-by: Peter Foley <pefoley2@pefoley.com>
GitOrigin-RevId: fa6a5a3a74cb822900111319c39a6a4793e4b588
Cr-Build-Id: 8694342822859151089
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694342822859151089
Copybot-Job-Name: zephyr-project-picolibc-copybot-downstream
Change-Id: Ia5ce542526363245969e7230a3627a7aba36d8c2
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7339736
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>