include: zephyr: arch: add missing stddef.h/stdbool.h in cache.h
Add missing inclusion of stddef.h and stdbool.h to respectively define
size_t and bool types used in some cache.h function declarations.

This change prevents build errors like:

.../include/zephyr/arch/cache.h:105:41: error: unknown type name 'size_t'
  105 | int arch_dcache_flush_range(void *addr, size_t size);
      |                                         ^~~~~~

(cherry picked from commit be62ee205adedb31b56f43d3fa5b9adee39b365a)

Original-Original-Signed-off-by: Etienne Carriere <etienne.carriere@st.com>
Original-GitOrigin-RevId: be62ee205adedb31b56f43d3fa5b9adee39b365a
Original-Cr-Build-Id: 8700425573583840625
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8700425573583840625
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I962923af1bd489f4fc6d0bb2461978d85c1a1ddf
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7066114
Original-Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
GitOrigin-RevId: 8f2b2fb49ca49ce39fb829f606d69c761eaa19e6
Cr-Build-Id: 8692665779950486545
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692665779950486545
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I62e8b502c183f8c9183e0f5837cd4f654c9f8b14
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7477419
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>