Bluetooth: SMP: Fix compilation with debugs enabled
This fix following compilation error if CONFIG_BLUETOOTH_DEBUG_SMP
is defined:

In file included from net/bluetooth/smp.c:44:0:
net/bluetooth/smp.c: In function 'bt_smp_irk_matches':
net/bluetooth/smp.c:681:31: error: 'val' undeclared
    (first use in this function)
  BT_DBG("IRK %s bdaddr %s", h(val, 16), bt_addr_str(addr));

Original-Change-Id: I3350620f1f7dc929b949b4483178df66dde55198
Original-Signed-off-by: Szymon Janc <szymon.janc@tieto.com>
GitOrigin-RevId: ada9a6f66fa39d2675ca057e876e91399e361b67
Cr-Build-Id: 8694909073039450241
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694909073039450241
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ia5992ccab7ba5ab69fd45bbddfaa657738cf81e8
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7291094
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>