drivers: gpio: max14906: Fix initialization
Found when building with clang with -Winitializer-overrides:

drivers/gpio/gpio_max14906.c:495:29: error: initializer overrides prior
initialization of this subobject [-Werror,-Winitializer-overrides]
  495 | DT_INST_FOREACH_STATUS_OKAY(GPIO_MAX14906_DEVICE)
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~

(cherry picked from commit 6d7b8b6b2d9951f5797a5de2f60c14143e87cc6d)

Original-Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Original-GitOrigin-RevId: 6d7b8b6b2d9951f5797a5de2f60c14143e87cc6d
Original-Cr-Build-Id: 8692520994521211601
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692520994521211601
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I232a0c9e6b5a9f7264ceb70ee3a399186a23cd5c
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7489351
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Commit-Queue: Jeremy Bettis <jbettis@chromium.org>
Original-Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
Original-Tested-by: Jeremy Bettis <jbettis@chromium.org>
GitOrigin-RevId: c1aa9c400c77dfaa542b8944197a1e74b8d19efb
Change-Id: I4dee4c9cc77c1a6a3430d47d146571d9f98cd594
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7505537
Reviewed-by: Dawid Niedźwiecki <dawidn@google.com>
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Tested-by: Jon Murphy <jpmurphy@google.com>
Commit-Queue: Jon Murphy <jpmurphy@google.com>