Add compile-time error message for when PB_FIELD_32BIT is needed (#680, #827)
Messages that are larger than 64 kB need a compilation option to use 32-bit type
for pb_size_t. Previously this would be indicated by FIELDINFO_DOES_NOT_FIT error
which is not clear to the actual cause.

This commit adds a new check with more clear error message:
test.pb.c:14:2: error: #error Enable PB_FIELD_32BIT to support messages exceeding 64kB in size: Message1

Also clarified some comments.

(cherry picked from commit 2da421befe1b91a3645807f5e8a7a99be0f323a7)

Original-GitOrigin-RevId: 2da421befe1b91a3645807f5e8a7a99be0f323a7
Original-Change-Id: I499f5c13aa5e59613fae992a4866b8750e6763f6
GitOrigin-RevId: 99b128e8d58a22065157c61d0741e6f63976cb03
Cr-Build-Id: 8693812001654323569
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693812001654323569
Copybot-Job-Name: zephyr-project-nanopb-copybot-downstream
Change-Id: I5ff069dda245c2d03d4e3df58c5bb6235eb50f81
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7378064
Commit-Queue: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>