drivers: input: Fix uninitialized closest_mv variable warning
Building with GCC 9.4.0 gives the following warning/error:

  error: closest_mv may be used uninitialized in this function

This commit fixes it.

(cherry picked from commit 35502592a7c702954697660f390b46e4912f8c56)

Original-Original-Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>
Original-GitOrigin-RevId: 35502592a7c702954697660f390b46e4912f8c56
Original-Change-Id: I77671c8a9bdbcbf026837902c2e50b283ab16176
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5356021
Original-Commit-Queue: Tristan Honscheid <honscheid@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Reviewed-by: Tristan Honscheid <honscheid@google.com>
Original-Tested-by: Tristan Honscheid <honscheid@google.com>
GitOrigin-RevId: 0d0cc67cab15fd8a8717ec1cd39b553b4ca52370
Cr-Build-Id: 8693067921100781825
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693067921100781825
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I3ce6d0b9e8a4a742004efe0e4ab8ab0e00f2cfbf
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7432715
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>