tests: net: lib: http_server: Check response
Building with clang, it warns:

tests/net/lib/http_server/core/src/main.c:1400:19: error: variable
'http1_header_capture_common_response' is not needed and will not be
emitted [-Werror,-Wunneeded-internal-declaration]
static const char http1_header_capture_common_response[]
                  ^                             = "HTTP/1.1 200\r\n"

Add a check to make sure the response actually matches the expected
response.

(cherry picked from commit a9c5b72a6f8014b03348555cbf84a91c04085d58)

Original-Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Original-GitOrigin-RevId: a9c5b72a6f8014b03348555cbf84a91c04085d58
Original-Cr-Build-Id: 8719292399802454161
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8719292399802454161
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: If2f07d57c0d46a977a66346365311280565163c4
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6398692
Original-Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: edb070d42be07ef4322c24eb8c0471cf95e7b81d
Cr-Build-Id: 8692825863232243105
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692825863232243105
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ife3cfdfbc33d192cc1336171b0d49b6680ce792b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7459771
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>