entropy: gd32: Fix build error
entropy_gd32_recover() had not return type defined causing the
following issue when building:

drivers/entropy/entropy_gd32.c:61:8: error: return type defaults to
'int' [-Werror=implicit-int]

Fix it and change the function to void since it was returning a
constant 0 that is never checked or used.

(cherry picked from commit 4690b7f966a58cb5c68c15442d11d17d22866026)

Original-Original-Signed-off-by: Flavio Ceolin <flavio@hubblenetwork.com>
Original-GitOrigin-RevId: 4690b7f966a58cb5c68c15442d11d17d22866026
Original-Cr-Build-Id: 8692226556012859633
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692226556012859633
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I956f4a4fc04ed7cb4d8b93be9845aa3c2adc57be
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7494817
Original-Tested-by: Dawid Niedźwiecki <dawidn@google.com>
Original-Commit-Queue: Dawid Niedźwiecki <dawidn@google.com>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Reviewed-by: Dawid Niedźwiecki <dawidn@google.com>
GitOrigin-RevId: 5572342a57882ec161d4512daf1b4fb164ed8640
Change-Id: Ie9781495e9f68b9069aa9b22ce0117a35a7b318c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7507645
Reviewed-by: Rob Barnes <robbarnes@google.com>
Reviewed-by: Alex Jacobs <aljacobs@google.com>
Tested-by: Jon Murphy <jpmurphy@google.com>