drivers: wifi: airoc: add missing header
Add a missing log.h error, fixes a build error:

airoc_whd_hal_common.c:14:40: error: expected ')' before numeric

constant airoc_whd_hal_common.c:32:17: error: implicit declaration of
function

Tested with: west build -p -b rpi_pico/rp2040/w samples/net/wifi/shell

Original-Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: 99db9625f9b5a8909a2fd6e894121d3bcb4099ea
Cr-Build-Id: 8682124993671113985
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8682124993671113985
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I2dbd2aab09a8ad2344e7782042457253147827f0
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7836198
Tested-by: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>