Bluetooth: host: Fix undefined reference to bt_le_adv_lookup_legacy
Fix undefined referenc to bt_le_adv_lookup_legacy in bt_le_oob_get_local
when bt_le_oob_get_local is used in a central only application.

Original-Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>
GitOrigin-RevId: d1469ecf26d1d98f12942fc2e7174e7f9a5d9c8a
Cr-Build-Id: 8693839842265224113
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693839842265224113
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ib8152a320f1e1ba4ae7a05d9548a94ffa631259e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7376128
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>