drivers: flash: mark unused argument
```
zephyr/include/zephyr/drivers/flash.h:113:63: error:
unused parameter ‘p’ [-Werror=unused-parameter]
  113 | int flash_params_get_erase_cap(const struct flash_parameters *p)
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```

Original-Fixes:
Original-Signed-off-by: Vasilii Aleksandrov <vasilii.aleksandrov@gmail.com>
GitOrigin-RevId: 90644fe62a802822c9c0f4a4640293d2f17016b9
Cr-Build-Id: 8681286970762046705
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8681286970762046705
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I17331c3c78812655414ba3ce1e339de266d55515
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7864721
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Tested-by: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>