drivers/spi/spi_xlnx_axi_quadspi: Build fix w CONFIG_SPI_ASYNC
Fix a build error when CONFIG_SPI_ASYNC is set.
The issue was detected by CI

```
spi_xlnx_axi_quadspi.c: In function 'xlnx_quadspi_isr':
spi_xlnx_axi_quadspi.c:489:21: error: 'ctx' undeclared
  489 |                 if (ctx->asynchronous) {
      |                     ^~~
```

(cherry picked from commit 0cf89bb8b41aeb039ea373efc0766eeb64cccc3f)

Original-Original-Signed-off-by: Alberto Escolar Piedras <alberto.escolar.piedras@nordicsemi.no>
Original-GitOrigin-RevId: 0cf89bb8b41aeb039ea373efc0766eeb64cccc3f
Original-Change-Id: I1b108f099ec46f76b6c3dcbfd9a49f90652f5d7e
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5694418
Original-Reviewed-by: Keith Short <keithshort@chromium.org>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: Keith Short <keithshort@chromium.org>
Original-Tested-by: Keith Short <keithshort@chromium.org>
GitOrigin-RevId: b04e61a405c2dee9ffb2ebcdf10ec1497193731b
Cr-Build-Id: 8692989153222372865
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692989153222372865
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I3814f592c1c42fb9b41aad6b097463c46f989c52
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7440441
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>