Bluetooth: add drivers to include path
Compiling without the drivers prefix causes the following type of
compiler error:

include/uart.h:42:21: fatal error: pci/pci.h: No such file or directory

Original-Change-Id: I99cd814708e74ed4722e5e906819497010263337
Original-Signed-off-by: Anas Nashif <anas.nashif@intel.com>
GitOrigin-RevId: 3aab249aa04716a9ffecd80c03e515948663bc7a
Cr-Build-Id: 8694772501779162609
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694772501779162609
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I6bed5b8e5caa62b42f3ff875acff1046b1fe9fe1
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7300998
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>