bluetooth: mesh: shell:  Fix warning when building with newlib
If we use newlib the isdigit (and other similar functions) return an
error as char can possibly be viewed as signed:

usr/include/ctype.h:57:54: error: array subscript has type ‘char’ [-Werror=char-subscripts]
 #define __ctype_lookup(__c) ((__ctype_ptr__+sizeof(""[__c]))[(int)(__c)])

Explicity cast to unsigned char so we deal with both this warning and
possible warning when -Wpointer-sign is enabled.

Original-Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
GitOrigin-RevId: c2862eda4d1e1ee45ff187399e9aa27c96d6bd93
Cr-Build-Id: 8694536526746984097
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694536526746984097
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ib893e7a2f08e038545a96c7a3f3ebe52b1ae5724
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7327339
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>