zbus: add MULTITHREADING dependency
Zbus uses mutexes internally that are available
only when MULTITHREADING is enabled so add
it to fix the following error:

/opt/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/
12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: zephyr/subsys/
zbus/libsubsys__zbus.a(zbus.c.obj): in function `k_mutex_init':
/builds/zephyr/mcuboot/zephyr/include/generated/syscalls/kernel.h:969:
undefined reference to `z_impl_k_mutex_init'

(cherry picked from commit 43d5f392090dd5060d056a527917312bef913864)

Original-Original-Signed-off-by: Bartosz Bilas <b.bilas@grinn-global.com>
Original-GitOrigin-RevId: 43d5f392090dd5060d056a527917312bef913864
Original-Change-Id: Ib409715118b81e9ba9438cd3a3564292cf764513
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5057233
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: Tristan Honscheid <honscheid@google.com>
Original-Reviewed-by: Tristan Honscheid <honscheid@google.com>
Original-Tested-by: Tristan Honscheid <honscheid@google.com>
GitOrigin-RevId: 1d127b52d591082a2910548ec6f726bf912bfde6
Cr-Build-Id: 8693114451436148193
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693114451436148193
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I440b0c18872d4721ab2001b23c8336415de428fd
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7427777
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>