tests: devicetree: Fix compile errors with GPIO define
A number of HALs define GPIO so we get a conflict in error of the form:

   main.c:12: error: "GPIO" redefined [-Werror]

Fix this by rename the defines in the test to "TEST_".  So GPIO becomes
TEST_GPIO.

Original-Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
GitOrigin-RevId: 7df2cad29aa51256ba52c29efef6126a34b516a8
Cr-Build-Id: 8693901271453221377
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693901271453221377
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I027fe89f98902e5b48d98558381f0e4564563097
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7372454
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>