drivers: rtc: Fix failing RV8803 driver build when int-gpios not used
This PR fixes the issue that building the driver with either
CONFIG_RTC_CALIBRATION=y or CONFIG_RTC_ALARM=y and without
'int-gpios' used will cause
'undefined reference to `rv8803_write_reg8'' error.

(cherry picked from commit f0a70b03660cd5442cc463cf9ba7603973c1a0a6)

Original-Original-Signed-off-by: Marcin Lyda <elektromarcin@gmail.com>
Original-GitOrigin-RevId: f0a70b03660cd5442cc463cf9ba7603973c1a0a6
Original-Cr-Build-Id: 8725724783141066929
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8725724783141066929
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I0f4b026c139e797ca1a515563cd75feba75a9cf9
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6175305
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: Keith Short <keithshort@chromium.org>
Original-Reviewed-by: Keith Short <keithshort@chromium.org>
Original-Tested-by: Keith Short <keithshort@chromium.org>
GitOrigin-RevId: e420f9a76b48812c6d2c3a6390807f64b8ba3e0e
Cr-Build-Id: 8692879179581421665
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692879179581421665
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I55391100abe50b32aa33a17f1776aacf8cceaf6f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7452898
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>