Bluetooth: Add bt_conn_enc_key_size function
This patch adds bt_conn_enc_key_size function which will be used
by application to check encryption keys size of a encrypted connection.
This will be used especialy by GATT applications, because some
attributes to be accessed require encryption with specified
minimum encryption key length.

> ACL Data RX: Handle 64 flags 0x02 dlen 7         [hci0] 708547.536685
      ATT: Read Request (0x0a) len 2
        Handle: 0x0003
< ACL Data TX: Handle 64 flags 0x00 dlen 9         [hci0] 708547.544302
      ATT: Error Response (0x01) len 4
        Read Request (0x0a)
        Handle: 0x0003
        Error: Insufficient Encryption Key Size (0x0c)

Original-Change-Id: Idbc9afde7ec80504898bd8d1e193f3e71a93f3f9
Original-Signed-off-by: Mariusz Skamra <mariusz.skamra@tieto.com>
GitOrigin-RevId: 992237bc514f0fe2906eb1f903520dd1cf643415
Cr-Build-Id: 8694845434596128161
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694845434596128161
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Icfa04fdc83d6752fed96c01b3f1d7b692734f43f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7295438
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>