drivers: rtc: maxim,ds3231: avoid compilation error
Because of wrong integer type syntax following error occurred:

drivers/rtc/rtc_ds3231.c:361:76: error: unknown type name 'u'
  361 | static int rtc_ds3231_alarm_get_supported_fields(
      |                    const struct device *dev, u int16_t id,
      |                                              ^

(cherry picked from commit cca2053448c3d7a2abf699fd12ac29a34bbd0e25)

Original-Original-Signed-off-by: Stephan Linz <linz@li-pro.net>
Original-GitOrigin-RevId: cca2053448c3d7a2abf699fd12ac29a34bbd0e25
Original-Cr-Build-Id: 8723776949373603889
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8723776949373603889
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I454e92d0bcf9676399461b1d4ac5830a847dd66e
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6234543
Original-Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: 1b8ca01f2b244adde9dc6f99fbe860ff80435dd7
Cr-Build-Id: 8692864854294522737
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692864854294522737
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I54456de75b90562528edcd08d4349b85d71ffac8
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7455076
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>