test: net: shell Remove unused function
Building with clang warns:

tests/net/shell/src/main.c:110:31: error: unused function 'if_get_addr'
[-Werror,-Wunused-function]
static inline struct in_addr *if_get_addr(struct net_if *iface)
                              ^

(cherry picked from commit 7179284a0c5e4ca2d8fffb3e35b13d40cdf7d5d9)

Original-Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Original-GitOrigin-RevId: 7179284a0c5e4ca2d8fffb3e35b13d40cdf7d5d9
Original-Cr-Build-Id: 8723142769276654049
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8723142769276654049
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I86024542fe5b1735f5a1320f919ab14d40cf3323
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6257274
Original-Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: bda2fa84d9b546c5f3ed832f3cd12f70267e054d
Cr-Build-Id: 8692857091111002929
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692857091111002929
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ib4c7da8c682f2b14fa613fe205258fc5f7314473
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7455894
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>