sys: atomic_c: skip syscall tracing
This skips syscall tracing on atomic_c.h, as the compiler
does not like "({ ... tracing code ... })" and complains:

  error: expected identifier or '(' before '{' token

Even though there is already a '(' before '{'.

(cherry picked from commit 5fc96ff9d70f7828b5eada42de04c521cd0904e1)

Original-Original-Signed-off-by: Daniel Leung <daniel.leung@intel.com>
Original-GitOrigin-RevId: 5fc96ff9d70f7828b5eada42de04c521cd0904e1
Original-Change-Id: Ib0a9216c35e69f88edaf7e3850053bd7d5bba3fc
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5196926
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Reviewed-by: Tristan Honscheid <honscheid@google.com>
Original-Tested-by: Tristan Honscheid <honscheid@google.com>
Original-Commit-Queue: Tristan Honscheid <honscheid@google.com>
GitOrigin-RevId: b7cabd14aeeae263b5c34f61d688f5c240adc1e6
Cr-Build-Id: 8693092994145856641
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693092994145856641
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I388da77299a638fa37bb73eb18f14f95875b2e53
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7430226
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>