net: mqtt: Fix error of `size_t` formatting with `PRIu16`
This addresses the following warning building with `CONFIG_64BIT=y`:

    error: format '%hu' expects argument of type 'int', but argument X has
    type 'size_t' {aka 'long unsigned int'}

(cherry picked from commit de1643d8fb0725b457098e2558a4902980e0284f)

Original-Original-Signed-off-by: Chen Xingyu <hi@xingrz.me>
Original-GitOrigin-RevId: de1643d8fb0725b457098e2558a4902980e0284f
Original-Cr-Build-Id: 8730213107226609921
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8730213107226609921
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I6a0367f4c2be4c0c2c4bf2a4aa66efd89cc55170
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6052087
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: 828e19a954f4195841a94f7b0ccfbb13000ca09e
Cr-Build-Id: 8692907370688804145
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692907370688804145
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I01b8e74cdf691d31992c2717200acb4c15ec080c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7448673
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>