net: ethernet: Fix build without -fpermissive
Fix ethernet_hw_caps initialization in ethernet.h for
strict type checking.

g++-12: include/zephyr/net/ethernet.h:957:38: error: invalid \
 conversion from 'int' to 'ethernet_hw_caps' [-fpermissive]

(cherry picked from commit b4f940d654a223e8aaa283d74dddb4bdb554cf92)

Original-Original-Signed-off-by: Daniel Nicoletti <dantti12@gmail.com>
Original-GitOrigin-RevId: b4f940d654a223e8aaa283d74dddb4bdb554cf92
Original-Cr-Build-Id: 8716039703355817313
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8716039703355817313
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I0a02fcea1a4c7831977ce08643a70fd054603780
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6507528
Original-Reviewed-by: Keith Short <keithshort@chromium.org>
Original-Tested-by: Keith Short <keithshort@chromium.org>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: Keith Short <keithshort@chromium.org>
GitOrigin-RevId: 9e2f0ae58cb303adb9b12805ac210428d70a7c8a
Cr-Build-Id: 8692802999006974193
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692802999006974193
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I4691804802fd87e124365f5123e61d91293d94b7
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7462107
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>