Bluetooth: Fix build if CONFIG_BLUETOOTH_DEBUG_HCI_CORE is enabled
If CONFIG_BLUETOOTH_DEBUG_HCI_CORE is enabled it causes the following

hci_core.c:514:12: error: 'struct bt_hci_evt_encrypt_key_refresh_complete' has no member named 'encrypt'
         evt->encrypt);
            ^

Original-error:
Original-Change-Id: I1983653eba40b9aea6b19572b39a285883f00450
Original-Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>
GitOrigin-RevId: d412b7d799e1220a32358a7845ba980eb56b2ff1
Cr-Build-Id: 8694909073039450241
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694909073039450241
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ie04e6cfcdf97016c9fcdb90ce70ceb018380c40b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7291069
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>