scripts: gen_kobject_list: Fix error log call
A trivial bug that caused the following error when this situation
actually happened:

  Too many thread objects (21)
  Traceback (most recent call last):
    File "/zephyr/scripts/gen_kobject_list.py", line 307, in <module>
      main()
    File "/zephyr/scripts/gen_kobject_list.py", line 281, in main
      -(-thread_counter // 8))
  TypeError: write() takes exactly one argument (2 given)

With this commit, the detected error is printed correctly, e.g:

  Too many thread objects (21)
  Increase CONFIG_MAX_THREAD_BYTES to 3

Original-Signed-off-by: Tomasz Gorochowik <tgorochowik@antmicro.com>
GitOrigin-RevId: 8adf39aae3090791bb99c43c5a46d407c0bd93cb
Cr-Build-Id: 8694318669638106945
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694318669638106945
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I9a76343badacd3f700d6975a7efc1bd6838b436f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7342248
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>