drivers: eth_nxp_imx_netc: add missing netc_eth_get_ptp_clock argument
Fix build error:

eth_nxp_imx_netc.c:304: error: too few arguments to function
'netc_eth_get_ptp_clock'

Add the missing argument tested with:

west build -p -b imx943_evk/mimx94398/m33/ddr
samples/net/ethernet/tsn-switch

Original-Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: 80a6968ada37c4fee27fe19c16489a7fb161e105
Cr-Build-Id: 8682555327095220625
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8682555327095220625
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: If9372c849aeb6c138665d231c69fb458341be397
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7819490
Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
Tested-by: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: Jeremy Bettis <jbettis@chromium.org>
Tested-by: Jeremy Bettis <jbettis@chromium.org>