Bluetooth: tester: Handle Set Encryption Key Size command
This patch adds a command to the tester application that sets the
required encryption key size to access characteristic value or
descriptor.

> ACL Data RX: Handle 64 flags 0x02 dlen 8    [hci0] 16139.016504
      ATT: Write Request (0x12) len 3
        Handle: 0x0004
          Data: be
< ACL Data TX: Handle 64 flags 0x00 dlen 9    [hci0] 16139.024052
      ATT: Error Response (0x01) len 4
        Write Request (0x12)
        Handle: 0x0004
        Error: Insufficient Encryption Key Size (0x0c)

Change-Id: Ida8b0fdaffe2b1a941a0b87c8a11395a8b63ccd0
Original-Signed-off-by: Mariusz Skamra <mariusz.skamra@tieto.com>
GitOrigin-RevId: 50a13c5fc19b3df2d2187f209a72cf91f91b0b14
Cr-Build-Id: 8697429649647787153
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8697429649647787153
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7195258
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>