Bluetooth: Host: Fix build error with observer-only config
When building an observer-only build the check_pending_conn label would
result in CI warnings/errors due to this only being a C23 feature:

scan.c:692:1: error: label at end of compound statement is a C23 extension

Turns out the #ifdefs are completely unnecessary, and the code can simply
take advantage of IS_ENABLED(), which should get rid of the warning.

(cherry picked from commit 73b6f8bd4a4bde38c8678d750793d02ae3f43c14)

Original-Original-Signed-off-by: Johan Hedberg <johan.hedberg@silabs.com>
Original-GitOrigin-RevId: 73b6f8bd4a4bde38c8678d750793d02ae3f43c14
Original-Cr-Build-Id: 8699111924411895361
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8699111924411895361
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Ib80f97d3d81c268e68a296ba97fa3861f7f8e27a
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7120129
Original-Tested-by: Ting Shen <phoenixshen@chromium.org>
Original-Reviewed-by: Ting Shen <phoenixshen@chromium.org>
Original-Commit-Queue: Ting Shen <phoenixshen@chromium.org>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
GitOrigin-RevId: 756666e6867fbb624874702ee8dee7c18306dd9d
Cr-Build-Id: 8692649474654741537
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692649474654741537
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I78843eb3828f47ea4b7ee147c4e7c4dae20c88d9
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7479482
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>