net: utils: Fix unused function warning
Building with clang warns:

subsys/net/ip/utils.c:600:24: error: unused function 'pkt_calc_chksum'
[-Werror,-Wunused-function]
static inline uint16_t pkt_calc_chksum(struct net_pkt *pkt, uint16_t sum)
                       ^

pkt_calc_chksum is called by net_calc_chksum, which only exists when
CONFIG_NET_NATIVE_IP is defined.

(cherry picked from commit 67e07b7a4116815b2b1379d1a8c9f38cd99e457a)

Original-Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Original-GitOrigin-RevId: 67e07b7a4116815b2b1379d1a8c9f38cd99e457a
Original-Cr-Build-Id: 8723414561518963153
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8723414561518963153
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Ie9290977e6335d7ccfed3470eac8afac1c56e2f7
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6247192
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: d60b057f32206520aa01d29b1793fe4aa3ab27f7
Cr-Build-Id: 8692860255205235329
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692860255205235329
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I14a8eae0a8d33883e6d0b457f2babc9fab5c7aae
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7455583
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>