sys: timeutil: check for 32-bit time_t to avoid warning
A warning was propogated to error when building for
native_sim/native.

```
timeutil.h:519:17: error: result of comparison of constant \
  -9223372036854775808 with expression of type '__time_t' (aka 'long') \
  is always false [-Werror,-Wtautological-constant-out-of-range-compare]
```

This is due to the issue described in #90029.

Add workarounds for `timespec_to_timeout()` and `timespec_negate()`
until 90029 is resolved.

(cherry picked from commit d61a7a80ad9cd316460af2822bbaa5bdff318dbd)

Original-Original-Signed-off-by: Chris Friedt <cfriedt@tenstorrent.com>
Original-GitOrigin-RevId: d61a7a80ad9cd316460af2822bbaa5bdff318dbd
Original-Cr-Build-Id: 8713630084945030369
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8713630084945030369
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Iec2fdeaf813aa765bc6f128b9db772d2cbfce245
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6582206
Original-Tested-by: Jeremy Bettis <jbettis@chromium.org>
Original-Tested-by: Al Semjonovs <asemjonovs@google.com>
Original-Commit-Queue: Jeremy Bettis <jbettis@chromium.org>
Original-Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Reviewed-by: Al Semjonovs <asemjonovs@google.com>
GitOrigin-RevId: c53ec15a60783d497c64ae5e702579560bf7af97
Cr-Build-Id: 8692785280656480161
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692785280656480161
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Iac2a0081f65e9fdd1a09728d353cb44f706b12aa
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7463764
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>