samples: subsys: ipc: Fix warning of `size_t` formatting with `%.*s`
This addresses the following warning building with `CONFIG_64BIT=y`:

    error: field precision specifier '.*' expects argument of type 'int',
    but argument X has type 'size_t' {aka 'long unsigned int'}

(cherry picked from commit bb94c63fa2447af60d449fc1234c0cbb288168d5)

Original-Original-Signed-off-by: Chen Xingyu <hi@xingrz.me>
Original-GitOrigin-RevId: bb94c63fa2447af60d449fc1234c0cbb288168d5
Original-Cr-Build-Id: 8730286630880259329
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8730286630880259329
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I04404dddd3760fadef5bf92e15acbcfb614a766d
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6045627
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: 235ba66197e0145b27b0f9655d62a03867c528af
Cr-Build-Id: 8692911841416468593
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692911841416468593
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I9f5f07d5a80311eff3b536f8f161563764b66e31
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7448349
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>