net: Initialize unspec_addr to avoid -Werror=maybe-uninitialized
The variable 'unspec_addr' in net_dhcpv6_init() is implicitly
initialized on some platforms and optimization levels, but not
guaranteed to be initialized on all code paths when built with
compiler instrumentation.

This leads to a build failure with the strict
'-Werror=maybe-uninitialized' warning when code coverage flags are
enabled (e.g., via twister --coverage).

```
zephyr/subsys/net/lib/dhcpv6/dhcpv6.c:2325:26: error: ‘unspec_addr’
may be used uninitialized [-Werror=maybe-uninitialized]
         net_ipaddr_copy(&net_sin6(&unspec_addr)->sin6_addr,
```

(cherry picked from commit 79a7106f9d15865ecbab8c8f698aace7b09590dd)

Original-Original-Signed-off-by: Nikhil Namjoshi <nikhilnamjoshi@google.com>
Original-GitOrigin-RevId: 79a7106f9d15865ecbab8c8f698aace7b09590dd
Original-Cr-Build-Id: 8696371365796932305
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8696371365796932305
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I6cd8f3dca3976023615b0601a033858b9ba35ec7
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7230382
Original-Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
GitOrigin-RevId: 59b6ca55284e3a3641b6714397741c5e40f79436
Cr-Build-Id: 8692625244129440977
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692625244129440977
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Iff58be324e689da20c29a5e6094b51fb5d9a57e6
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7482557
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>