net: buf: Fix compilation with newlib libc
newlib is declaring __unused in cdef.h which was conflicting with
__unused member in struct net_buf. Use _unused name instead.

In file included from /work/Zephyr/project/zephyr-project/net/buf.c:27:0:
include/net/buf.h:38:14: error: declaration does not declare anything
    [-Werror]
           int __unused;
               ^

Original-cc1: all warnings being treated as errors
Original-Change-Id: I2df189a4d4aee0f982c2d28d24847052f6168d45
Original-Signed-off-by: Szymon Janc <ext.szymon.janc@tieto.com>
GitOrigin-RevId: b5c7b1baca9a7211953701853b5efb5fe3c76629
Cr-Build-Id: 8694815222550073457
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694815222550073457
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I2ff1d93023ccdccc24098d04c5286d27b233eba5
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7297669
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>