gpio: sx1509b: Fix address-of-packed-mem warning
The warning below appears once -Waddress-of-packed-mem is enabled:

/__w/zephyr/zephyr/drivers/gpio/gpio_sx1509b.c: In function
'port_write':
/__w/zephyr/zephyr/drivers/gpio/gpio_sx1509b.c:456:19: error: taking
address of packed member of 'struct sx1509b_pin_state' may result in an
unaligned pointer value [-Werror=address-of-packed-member]
  456 |  uint16_t *outp = &drv_data->pin_state.data;

To avoid the warning, use an intermediate void * variable.

More info in #16587.

(cherry picked from commit 710e03b99041e942a3ba8bb8ab41eb5506405e5a)

Original-Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>
Original-GitOrigin-RevId: 710e03b99041e942a3ba8bb8ab41eb5506405e5a
Original-Change-Id: Iffc9b617d5d8bed1e1e65bdcaaf7aef20f9f6164
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/3332179
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Reviewed-by: Tristan Honscheid <honscheid@google.com>
Original-Commit-Queue: Tristan Honscheid <honscheid@google.com>
GitOrigin-RevId: 7910d907d712f23d7236db5544eecb216f66202e
Cr-Build-Id: 8693663859494856737
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693663859494856737
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I6fd326ac1094b72768e063a51d808485c3cb626e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7386362
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>