scripts: dts: gen_defines: Fix issue if there are no compats
We get the following error:

  ValueError: max() arg is an empty sequence

if the compatiable section of the device tree is empty or doesn't exist.
Fix this by havingin max_len get a default value of 0.

Original-Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
GitOrigin-RevId: 299bfd0553b6e8ac1b63bbf8d54c08da332f91c2
Cr-Build-Id: 8694072468416197473
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694072468416197473
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ieff139486ea718d0ad8e4558aaed0389bedaa080
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7358763
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>