net: lwm2m: device object: Fix coverage compatibility
Starting with b1d24e425c3a30cdf1aed3c54c25a2518061accc (net: lwm2m:
device object: optionally store error list in settings), it was no
longer possible to build the code with coverage enabled when the
settings subsystem was disabled.

The build would fail with an error like this:

> subsys/net/lib/lwm2m/lwm2m_obj_device.c:262: undefined reference to
> `settings_name_steq'

This fixes #70923.

(cherry picked from commit ccc58b8ce54505e11eee28914dac1821143b6b98)

Original-Original-Signed-off-by: Reto Schneider <reto.schneider@husqvarnagroup.com>
Original-GitOrigin-RevId: ccc58b8ce54505e11eee28914dac1821143b6b98
Original-Change-Id: I6acefdaf9cddcdd9cc5ca61211adb876b6722b5e
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5423735
Original-Tested-by: Tristan Honscheid <honscheid@google.com>
Original-Reviewed-by: Tristan Honscheid <honscheid@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: Tristan Honscheid <honscheid@google.com>
GitOrigin-RevId: 8b5470289d8c9e17610c4419835c9d3fa9fae624
Cr-Build-Id: 8693049822557258897
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693049822557258897
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ic2ece34e8e2642d39c49a23965770414d0993fbc
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7434448
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>