xtensa: fix error: use of undeclared identifier 'intenable2'
This is likely a miss from:
df40dff6fb1 arch: xtensa: clean up interrupt handling

(cherry picked from commit 926efb8fc1a8f013da92d6c74dbdc87fc2654702)

Original-Original-Signed-off-by: William Tambe <williamt@cadence.com>
Original-GitOrigin-RevId: 926efb8fc1a8f013da92d6c74dbdc87fc2654702
Original-Cr-Build-Id: 8698908081405170945
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8698908081405170945
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I5bdd5e54520c5e09ffe457ae519136dc8cd106fe
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7129495
Original-Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
GitOrigin-RevId: 04f454f15e66a3c140d07b3d6aac25d801264a56
Cr-Build-Id: 8692647051261749617
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692647051261749617
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Iacbb4018be945be6a6c90b7fd77acaa096505ab0
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7479617
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>