samples: modules: lvgl: transparency: Fix supported pixel format check
Found while building with clang and -Wtautological-compare:

samples/modules/lvgl/screen_transparency/src/main.c:47:45: error:
bitwise or with non-zero value always evaluates to true
[-Werror,-Wtautological-bitwise-compare]

if (!(display_caps.supported_pixel_formats | PIXEL_FORMAT_ARGB_8888)) {
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~

(cherry picked from commit 37deb317c5637aa917a4ed75317e80f89d4931dc)

Original-Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Original-GitOrigin-RevId: 37deb317c5637aa917a4ed75317e80f89d4931dc
Original-Cr-Build-Id: 8725588887340772977
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8725588887340772977
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I74185d8f312c0b26e1e39b13292ae3e1105edc91
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6179518
Original-Commit-Queue: Keith Short <keithshort@chromium.org>
Original-Reviewed-by: Jonathon Murphy <jpmurphy@google.com>
Original-Tested-by: Keith Short <keithshort@chromium.org>
GitOrigin-RevId: 6801633ff78230afc37113ea7964d5b87813ebd8
Cr-Build-Id: 8692876761902365697
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692876761902365697
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ica3c9344291e314a37789db70428863586232b09
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7453193
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>