bluetooth: audio: Fix redundant initialization
When building the bluetooth.general.tester_le_audio test with clang and
-Winitializer-overrides, it warns:

subsys/bluetooth/audio/mpl.c:318:2: error: initializer overrides prior
initialization of this subobject [-Werror,-Winitializer-overrides]
  318 |         .add_group = NULL,
      |         ^~~~~~~~~~~~~~~~~
subsys/bluetooth/audio/mpl.c:317:15: note: previous initialization is here
  317 |         .add_track = NULL,
      |                      ^~~~

Remove redundant initializer for add_group which overlaps with add_track
in an anonymous union.

(cherry picked from commit 8ea64b7b33c0701f5b1084557ec17ed2f81594b2)

Original-Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Original-GitOrigin-RevId: 8ea64b7b33c0701f5b1084557ec17ed2f81594b2
Original-Cr-Build-Id: 8692045360469606417
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692045360469606417
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Icd28171c4600fd5ac426e03aceb93cf66d0b27d6
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7505898
Original-Reviewed-by: Dawid Niedźwiecki <dawidn@google.com>
Original-Commit-Queue: Dawid Niedźwiecki <dawidn@google.com>
Original-Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Original-Reviewed-by: Jon Murphy <jpmurphy@google.com>
Original-Tested-by: Dawid Niedźwiecki <dawidn@google.com>
GitOrigin-RevId: f13e72f9189c2adb4389d38937ebff6a0ecad02f
Change-Id: I4d0f4d5a97956e21ad64c69d2faf4a9db09ec312
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7514017
Tested-by: Jon Murphy <jpmurphy@google.com>
Reviewed-by: Brett Brotherton <bbrotherton@google.com>