llext: elf.h: fix wrong 32 bits length of elf64_rela fields
Fixes commit a9a82d557c72 ("llext: use elf_rela_t instead of elf_rel_t")

Also switch sign of (unused?) `r_addend` to unsigned.

Issue found thanks to the following warnings when compiling in 64bits:

```
/__w/zephyr/zephyr/include/zephyr/llext/elf.h:349:29: error:
  right shift count >= width of type [-Werror=shift-count-overflow]
     349 | #define ELF64_R_SYM(i) ((i) >> 32)
```

The name `elf64_word` was admittedly confusing.

(cherry picked from commit 7eb1d3d57d2d0c0484935199503de97815ea243c)

Original-https: //refspecs.linuxfoundation.org/elf/gabi4+/ch4.reloc.html
Original-Original-Signed-off-by: Marc Herbert <marc.herbert@intel.com>
Original-GitOrigin-RevId: 7eb1d3d57d2d0c0484935199503de97815ea243c
Original-Change-Id: I07e9e114004b0e6f3d89a6640e8670f1cd4d1b8e
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5369144
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: e64a6a9d70bd5abf93dfe9d2ade5fb70614f46c0
Cr-Build-Id: 8693065741100219505
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693065741100219505
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I8a3ec3a47dbc2f78538f9d248abda840c3355e63
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7432953
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>