tests: i2c_emul: Remove unused variable
Building with clang warns:

tests/drivers/i2c/i2c_emul/src/test_forwarding_buf.cpp:20:32: error:
unused variable 'targets' [-Werror,-Wunused-const-variable]
constexpr const struct device *targets[FORWARD_COUNT] = {
                               ^

(cherry picked from commit 782152f404b9dfd96f9922f62c466b8e4e06c953)

Original-Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Original-GitOrigin-RevId: 782152f404b9dfd96f9922f62c466b8e4e06c953
Original-Cr-Build-Id: 8723052172249940737
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8723052172249940737
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: Iafa99afc81c6bde3184a52e65aea36a59a2f48d7
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6261362
Original-Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: f92ef55618c6b38f3ad89fc7fafa670746f3768d
Cr-Build-Id: 8692854981942345489
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692854981942345489
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: If5fd583a4f2f6b92bca1ae4ccd3c450f30abdefb
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7454789
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>