Bluetooth: controller: Fix build error
.../ll_sw/nordic/lll/lll_scan.c: In function 'isr_tx':
.../ll_sw/nordic/lll/lll_scan.c:483:19: error: unused variable 'lll'
                                              [-Werror=unused-variable]
  483 |  struct lll_scan *lll = param;
      |                   ^~~

This fixes https://github.com/zephyrproject-rtos/zephyr/issues/29968.

Original-cc1: all warnings being treated as errors
Original-Signed-off-by: Andrzej Kaczmarek <andrzej.kaczmarek@codecoup.pl>
GitOrigin-RevId: a17952237f8e6e1719dc30ceef53b19ad40ccada
Cr-Build-Id: 8693940612966339281
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693940612966339281
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Idf23c05c4d560e57bd417ef158c45639177c6942
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7369961
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>