kernel: mem_slab: only define slab_ptr_is_good with assert enabled
Add a __ASSERT_ON guard around slab_ptr_is_good, as that is only used in
assertions and leaving it on seems to generate a build warning with some
clang versions:

kernel/mem_slab.c:207:20: error: unused function 'slab_ptr_is_good'
  207 | static inline bool slab_ptr_is_good(struct k_mem_slab *slab,...
      |                    ^~~~~~~~~~~~~~~~

(cherry picked from commit 328365989f278c581985ae3cd9510a4df14f82e9)

Original-Original-Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-GitOrigin-RevId: 328365989f278c581985ae3cd9510a4df14f82e9
Original-Change-Id: If196dd35272db76466cece7c44139e4c1ec98dc1
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5616301
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: faed25aa1a9718c8c3aed66ebfbfae39f645151f
Cr-Build-Id: 8693008678827941153
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693008678827941153
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I583b49550b8334ef6c09f96922147b8c01ffa2d4
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7438435
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>