MAINTAINERS: fix missing ":"
Add a missing ":" for "Drivers: Regulators", currently causing PR
assigner failure:

```
yaml.scanner.ScannerError: while scanning a simple key
  in "MAINTAINERS.yml", line 976, column 1
could not find expected ':'
  in "MAINTAINERS.yml", line 977, column 3
```

(cherry picked from commit 06e518265ccf7f9c4534b9e6dc0e85579a009432)

Original-Original-Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-GitOrigin-RevId: 06e518265ccf7f9c4534b9e6dc0e85579a009432
Original-Change-Id: I6101fdad4901946b52b2d5325a64e830ca7fc329
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4126993
Original-Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
GitOrigin-RevId: 1865926508573c5ea3a7692c3a830aa57de868c1
Cr-Build-Id: 8693381088958202401
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693381088958202401
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I0808e63ee1138a67a2e1a4b909c40dba60ad7d93
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7406288
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>