drivers: dma: Remove double parentheses in if statements
This patch fixes following compilation error when compiling using clang

drivers/dma/dma_stm32.c:364:42: error: equality comparison with
extraneous parentheses [-Werror,-Wparentheses-equality]
        if ((config->head_block->source_address == 0)) {
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
drivers/dma/dma_stm32.c:364:42: note: remove extraneous parentheses
around the comparison to silence this warning
        if ((config->head_block->source_address == 0)) {
            ~                                   ^   ~

(cherry picked from commit c0e1c5e09b4e0b9bc05b7878942e0e126ad5f2af)

Original-Original-Signed-off-by: Patryk Duda <pdk@semihalf.com>
Original-GitOrigin-RevId: c0e1c5e09b4e0b9bc05b7878942e0e126ad5f2af
Original-Change-Id: Iee89fda8184d8f71907bb554dbac827ef7fd1e05
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4579210
Original-Commit-Queue: Tristan Honscheid <honscheid@google.com>
Original-Reviewed-by: Tristan Honscheid <honscheid@google.com>
Original-Tested-by: Tristan Honscheid <honscheid@google.com>
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
GitOrigin-RevId: 3309b60aea3a8f0ab3e73150c014cb43df9ce609
Cr-Build-Id: 8693210350653451585
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693210350653451585
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: If4346222004e8388f2a66a8749085a49f404bdd8
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7417602
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>