bluetooth: Fix "struct bt_gatt_read_params" declaration
Compiling this declaration with a CXX compiler triggers the compiler

/home/sebo/zephyr/include/bluetooth/gatt.h:898:10: error: ‘struct
bt_gatt_read_params::<anonymous union>::__single’ invalid; an
anonymous union can only have non-static data members [-fpermissive]

Reading up on the standard, I was unable to find any mention of this
being valid C or CXX code (But reading the standard is not
straightforward). And I was unable to find any mechanism to make the
CXX compiler accept it (e.g. Changing the -std, or adding this as a
language extension e.g. -fms-extensions).

So we rewrite it to not declare the struct with the tag
"__single". There does not seem to be any reason for it to be declared
like this.

Original-error:
Original-Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>
GitOrigin-RevId: f61cd12bf89cf3d8755a6b49fb370f41c6726823
Cr-Build-Id: 8694589597225911713
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694589597225911713
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I1373badd7d0c0c50ee4b3819cab5c8a55d68b958
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7322851
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>