net: sntp: Namespace private SNTP definitions
SNTP implementation defined symbols like "MODE_MASK", which can easily
conflict with similary laxly defined symbols in other modules, and
indeed, we hit a case like that (below). So, prefix these symbols
consistently with "SNTP_", until more clear private namespacing
convention are made pervasive in Zephyr.

subsys/net/lib/sntp/sntp_pkt.h:14: error: "MODE_MASK" redefined
include/arch/arm/aarch32/cortex_a_r/cpu.h:17: note: this is the
  location of the previous definition

Original-Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>
GitOrigin-RevId: af3defd34e1c06e9fdc57da6c1b5c91a95c44023
Cr-Build-Id: 8694048377618400625
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694048377618400625
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I4b4613c397b2168030f9de2164db205d52226f57
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7360496
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>