drivers: bbram: stm32: add include to fix compilation error
Driver BBRAM for STM32 had a compilation error: "unknown type name
'RTC_TypeDef'" due to missing include file.

(cherry picked from commit b0e1e9f5fbf7f6b1f42fcc643d0e3b232b871c65)

Original-Original-Signed-off-by: Guillaume Gautier <guillaume.gautier-ext@st.com>
Original-GitOrigin-RevId: b0e1e9f5fbf7f6b1f42fcc643d0e3b232b871c65
Original-Change-Id: Id6f977355e848bee8cd0f93173a466e300b701ec
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5295751
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: 759338d50b20d26bd05cbf24fc10825d82282d0e
Cr-Build-Id: 8693076695425399937
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693076695425399937
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I5a69646411cf118b4f963dffc7c32c6161de0344
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7431882
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>