twister: runner: j-link: Fix parameter passing
To specify the serial number, JLink expects either one argument
('--dev-id=xxx') or two (e.g. '--dev-id' 'xxx'), but it can not deal
with a single one that is '--dev-id xxx'.

The problem has been introduced (or just made visible?) by commit
5ee42843205dcdfa1c9833282613731dee75c93c (twister: runner: j-link: use
dev-id instead of SelectEmuBySN) in PR #76931.

How to reproduce:

1. Create a HW configuration map, e.g.:

```
$ cat zephyr-hw-map-nrf52840dk-1.yml
- connected: true
  id: '683517317'
  platform: nrf52840dk/nrf52840
  product: nRF52840 DK 1
  runner: jlink
  serial: /dev/ttyACM-nrf-dk-1
```

2. Run test `logging.dictionary` with Twister:

```
$ west twister --platform nrf52840dk/nrf52840 --device-testing \
  --hardware-map zephyr-hw-map-nrf52840dk-1.yml -s logging.dictionary
```

3. The build will fail, and the `twister_harness.log` contains:

```
  "hardware"
  serial connection for /dev/ttyACM-nrf-dk-1
  device 683517317
  command: <snip>/bin/west flash --skip-rebuild --build-dir
  twister-out/<snip>/tests/subsys/logging/dictionary/logging.dictionary
  --runner jlink '--dev-id 683517317'
  flash device 683517317
  serial connection for /dev/ttyACM-nrf-dk-1
```
(note the '--dev-id 683517317' part)

4. Running the stated `west flash` command shows the following error
   message:

```
-- west flash: using runner jlink
FATAL ERROR: runner jlink received unknown arguments: ['--dev-id
  683517317']
```

(cherry picked from commit 7f1c3d1841f332de163266998f64b1016640c938)

Original-10: 21:24.375:DEBUG:twister_harness.device.factory: Get device type
Original-10: 21:24.375:DEBUG:twister_harness.device.hardware_adapter: Opening
Original-10: 21:24.376:DEBUG:twister_harness.device.hardware_adapter: Flashing
Original-10: 21:24.376:DEBUG:twister_harness.device.hardware_adapter: Flashing
Original-10: 21:24.590:ERROR:twister_harness.device.hardware_adapter: Could not
Original-10: 21:24.592:DEBUG:twister_harness.device.hardware_adapter: Closed
Original-Original-Signed-off-by: Reto Schneider <reto.schneider@husqvarnagroup.com>
Original-GitOrigin-RevId: 7f1c3d1841f332de163266998f64b1016640c938
Original-Cr-Build-Id: 8738508474594683537
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8738508474594683537
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I04637c163c120cfc5469e373b9d682fbfcd432c8
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5814316
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: 36e09ab9e7c59e79e46bb0811c9e68382ac5c3f2
Cr-Build-Id: 8692968494524072993
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692968494524072993
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I8a2e82f7cb2054fa53ba8b59ed82d9e3a2bdf402
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7442610
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>