sensors: default_rtio_sensor: fix build warning
Fix a build warning on 64 bit architectures:

zephyr/drivers/sensor/default_rtio_sensor.c:238:17: error: format '%zu'
expects argument of type 'size_t', but argument 2 has type 'uint32_t'
{aka 'unsigned int'}

num_channels type changed to uint32_t in 96175fcc47.

(cherry picked from commit d53b1a1c0efcd784239d5a73eefd25a62ced6f30)

Original-Original-Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-GitOrigin-RevId: d53b1a1c0efcd784239d5a73eefd25a62ced6f30
Original-Change-Id: I8e020edf97b70806ef622ded89f9f30098664860
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4921895
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Reviewed-by: Keith Short <keithshort@chromium.org>
Original-Tested-by: Keith Short <keithshort@chromium.org>
Original-Commit-Queue: Keith Short <keithshort@chromium.org>
GitOrigin-RevId: 4c0dd84455b4851ea1f9f26e5328187f4283714e
Cr-Build-Id: 8693142186010304833
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693142186010304833
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ibb8d281f5bc82c4ca615e5b130ae99583184c9ce
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7424665
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>