dts: arm: st: add stm32c071 dtsi files
- provide support for the STM32C071 serie
- add stm32g0-flash-controller compatible on flash node
to fix CI issue on undefined reference to
`flash_stm32_page_layout'

(cherry picked from commit 0ef33f3e7752e6c785957e79436148eefe57c54d)

Original-Original-Signed-off-by: Fabrice DJIATSA <fabrice.djiatsa-ext@st.com>
Original-GitOrigin-RevId: 0ef33f3e7752e6c785957e79436148eefe57c54d
Original-Cr-Build-Id: 8727764308049365969
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8727764308049365969
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: I778e7f3972c369e0c64f626ed75345ddaf6faf9f
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6114347
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: b6bb4fee597dae5eedd324d95d2ee145c670ceee
Cr-Build-Id: 8692887978930619265
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692887978930619265
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I40f532cc87c44c1f88f0218898b431fd509b7a14
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7451250
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>