soc: st: common: stm32cube_hal: add assertions glue for HAL2
The STM32Cube HAL2 uses different hooks for assertion failures.
Attempting to enable HAL assertions on series using HAL2 right now
results in a build failure because we don't provide these hooks.

For example:
  west build samples/net/dhcpv4_client/ -b nucleo_c5a3zg
  -DCONFIG_ASSERT=y -DCONFIG_USE_STM32_ASSERT=y -p

results in the following messages (shortened for clarity):
  [293/298] Linking C executable zephyr/zephyr_pre0.elf
  FAILED: zephyr/zephyr_pre0.elf zephyr/zephyr_pre0.map
  ld.bfd: in function `HAL_RCC_PSI_GetConfig':
  .../stm32c5xx/drivers/hal/stm32c5xx_hal_rcc.c:1596:
       undefined reference to `assert_dbg_param_failed'
  ld.bfd: in function `HAL_ETH_SetConfig':
  .../stm32c5xx/drivers/hal/stm32c5xx_hal_eth.c:1465:
       undefined reference to `assert_dbg_state_failed'

Add glue code needed for compatibility with HAL2 and, while at it, also
clean up the HAL1-specific hook.

Original-Signed-off-by: Mathieu Choplain <mathieu.choplain-ext@st.com>
GitOrigin-RevId: 1547f729c62b03fbff8e06d89c0a1014b69d6371
Cr-Build-Id: 8680539547227215297
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8680539547227215297
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I30f3b7d9d660187676e1d8f52e2fb354907b149e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7875040
Commit-Queue: Rob Barnes <robbarnes@google.com>
Tested-by: Rob Barnes <robbarnes@google.com>
Reviewed-by: Rob Barnes <robbarnes@google.com>
Tested-by: copybot@chops-service-accounts.iam.gserviceaccount.com <copybot@chops-service-accounts.iam.gserviceaccount.com>