kernel: cmake: fix k_sleep compilation error for single thread
Fix k_sleep compilation error:
[build] ... syscalls/kernel.h:135: undefined reference to `z_impl_k_sleep'
for single thread applications (CONFIG_MULTITHREADING = n).
The shed.c contains source code which must be present also
in single thread applications.

(cherry picked from commit cc4ffb2a54bd136095100c899f1b875fd1ce6f9d)

Original-Original-Signed-off-by: Andrej Butok <andrey.butok@nxp.com>
Original-GitOrigin-RevId: cc4ffb2a54bd136095100c899f1b875fd1ce6f9d
Original-Change-Id: I3f140cccc99e8bad0bd9586b1f7de6c37ee02e1a
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5121990
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Original-Reviewed-by: Yuval Peress <peress@google.com>
Original-Tested-by: Yuval Peress <peress@google.com>
Original-Commit-Queue: Yuval Peress <peress@google.com>
GitOrigin-RevId: a4757391e433bb4aaa8e7c078f05db471f9d56dc
Cr-Build-Id: 8693103384354449825
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693103384354449825
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I37234e036c14e9beb48b3f817d392eeba8231210
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7429172
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>