Bluetooth: Mesh: Fix compiler warning
When building with an LLVM toolchain get the following warning:

bluetooth/mesh/pb_adv.c:774:4: error: expression which evaluates to zero
treated as a null pointer constant of type
'void *' [-Werror,-Wnon-literal-null-conversion]
                        PROV_BEARER_LINK_STATUS_SUCCESS);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fix by adding a cast to (void *).

(cherry picked from commit 0342deb5d930b59b3d15fa84256ecd3ed4643c76)

Original-Original-Signed-off-by: Kumar Gala <kumar.gala@intel.com>
Original-GitOrigin-RevId: 0342deb5d930b59b3d15fa84256ecd3ed4643c76
Original-Change-Id: I54fc7a4be5e860c3b2536e9a721736dcbe4e16c1
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4345340
Original-Reviewed-by: Keith Short <keithshort@chromium.org>
Original-Tested-by: Keith Short <keithshort@chromium.org>
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Commit-Queue: Keith Short <keithshort@chromium.org>
GitOrigin-RevId: 662c39a6e998af0b0c397a4b8e4a28c609a106f5
Cr-Build-Id: 8693326771132667633
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693326771132667633
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I5b7d608b5349381f05130c08ce60759f2bf67ecc
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7410252
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>