Fix microkernel app_kernel benchmark
The event portion of the app_kernel benchmark no longer outputs the following
(abbreviated) error message:
   <path to project>/app_kernel/src/event_b.c:86 Error: tick occurred

This error was occurring as the benchmark test had hard-coded the value of
the event TEST_EVENT to 0 instead of defining it in the prj.mdef file.
Consequently, the system was using event 0 for the tick event; every time
task_event_send(TEST_EVENT) was invoked, the system treated it as a tick event.

Original-Change-Id: I1a785a6594415bd4b0300d382f76a6d768641864
Original-Signed-off-by: Peter Mitsis <peter.mitsis@windriver.com>
GitOrigin-RevId: 249d6232105c958ae1c97e35c75023864b4df3d1
Cr-Build-Id: 8694879146164828977
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694879146164828977
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I5626045ba3b7b510f099c04c9e268e782f221404
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7292688
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>