modem: wncm14a2a: fix warning with isalpha/isdigit
When building with arm-clang we get warnings of the type:

wncm14a2a.c:828:14: error: array subscript is of type
			   'char' [-Werror,-Wchar-subscripts]:
                } else if (isalpha(c2) != 0) {
                           ^~~~~~~~~~~

Fix this by adding explicit casts to (int) when callinng isalpha()
or isdigit().

(cherry picked from commit 1a5d47ef6d898707b0eac19b277084ccd6f81756)

Original-Original-Signed-off-by: Kumar Gala <kumar.gala@intel.com>
Original-GitOrigin-RevId: 1a5d47ef6d898707b0eac19b277084ccd6f81756
Original-Change-Id: Id1d41e39d6edd975f6e44ee26313adba5a043e87
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4474962
Original-Commit-Queue: Tristan Honscheid <honscheid@google.com>
Original-Tested-by: Tristan Honscheid <honscheid@google.com>
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Original-Reviewed-by: Tristan Honscheid <honscheid@google.com>
GitOrigin-RevId: 8c8bd2a0d66f838c6402e697515c0868793e0b50
Cr-Build-Id: 8693283942708556769
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693283942708556769
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I59d28af3894786803dac5bab45d3dee09d1f5d14
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7413402
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>