shell: mqtt: Avoid using POSIX function names
This commit fixes this error seen in CI so that things
work even if CONFIG_POSIX_API is enabled.

subsys/shell/backends/shell_mqtt.c:727:12: error:
  conflicting types for 'write'; have
 'int(const struct shell_transport *, const void *, size_t,  size_t *)'
  727 | static int write(const struct shell_transport *transport,
                         const void *data, size_t length)

include/zephyr/posix/unistd.h:230:9: note: previous declaration
 of 'write' with type
 'ssize_t(int,  const void *, size_t)'
  230 | ssize_t write(int file, const void *buffer, size_t count);

subsys/shell/backends/shell_mqtt.c:787:12: error:
 conflicting types for 'read'; have
 'int(const struct shell_transport *, void *, size_t,  size_t *)'
  787 | static int read(const struct shell_transport *transport,
                        void *data, size_t length, size_t *cnt)

include/zephyr/posix/unistd.h:231:9: note: previous declaration
 of 'read' with type
 'ssize_t(int,  void *, size_t)'
  231 | ssize_t read(int file, void *buffer, size_t count);

(cherry picked from commit e158c1729aa5ec3286c165267dfa26ebbc679d30)

Original-Original-Signed-off-by: Jukka Rissanen <jukka.rissanen@nordicsemi.no>
Original-GitOrigin-RevId: e158c1729aa5ec3286c165267dfa26ebbc679d30
Original-Change-Id: I0ed162550bd3eb46033c9e644dab09a2d7e29e49
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/5407485
Original-Tested-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Reviewed-by: Keith Short <keithshort@chromium.org>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
GitOrigin-RevId: 410a973ccfd396124d382ac9d0d35c3bfb56ba0d
Cr-Build-Id: 8693054043427284545
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693054043427284545
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ib0f660278cbfa57719aeeea9993a0cb4385f6cf6
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7434185
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>