net: Fix warning of `size_t` formatting with `%.*s`
This addresses the following warning building with `CONFIG_64BIT=y`:

    error: field precision specifier '.*' expects argument of type 'int',
    but argument X has type 'size_t' {aka 'long unsigned int'}

(cherry picked from commit 50f23500b8c62a7fca4d35f0b4ec9434ceab5fed)

Original-Original-Signed-off-by: Chen Xingyu <hi@xingrz.me>
Original-GitOrigin-RevId: 50f23500b8c62a7fca4d35f0b4ec9434ceab5fed
Original-Cr-Build-Id: 8730286630880259329
Original-Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8730286630880259329
Original-Copybot-Job-Name: zephyr-main-copybot-downstream
Original-Change-Id: If7f35e3e818da174223b1e4af3e96a4d352a95bb
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6045626
Original-Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Original-Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Original-Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
GitOrigin-RevId: 7a4019edf6c6b2421809e558eed903d9f9596c81
Cr-Build-Id: 8692911841416468593
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8692911841416468593
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I34aafdf333137034773a95c53d42ad5954df488a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7448348
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>