bluetooth: controller: Fix build with BT_HCI_VS_EXT disabled
[216/319] Building C object zephyr/subsys/bluetooth/controller/
  CMakeFiles/subsys__bluetooth__controller.dir/hci/hci.c.obj
zephyrproject/zephyr/subsys/bluetooth/controller/hci/hci.c:
   In function 'hci_vendor_cmd_handle_common':
zephyrproject/zephyr/subsys/bluetooth/controller/hci/hci.c:5459:17:
   warning: implicit declaration of function 'vs_set_min_used_chans';
   did you mean 'll_set_min_used_chans'? [-Wimplicit-function-declaration]
 5459 |                 vs_set_min_used_chans(cmd, evt);
      |                 ^~~~~~~~~~~~~~~~~~~~~
      |                 ll_set_min_used_chans
....
zephyr-sdk-0.15.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.1.0/../
  ../../../arm-zephyr-eabi/bin/ld.exe: zephyr/subsys/bluetooth/controller/
  libsubsys__bluetooth__controller.a(hci.c.obj): in function
   `hci_vendor_cmd_handle_common':
zephyrproject/zephyr/subsys/bluetooth/controller/hci/hci.c:5459: undefined
   reference to `vs_set_min_used_chans'
collect2.exe: error: ld returned 1 exit status

(cherry picked from commit 6ca2dac6a31e6d914ace5baed76293878ca3e793)

Original-Original-ninja: build stopped: subcommand failed.
Original-Original-Signed-off-by: Szymon Janc <szymon.janc@codecoup.pl>
Original-GitOrigin-RevId: 6ca2dac6a31e6d914ace5baed76293878ca3e793
Original-Change-Id: I00e4a1cd1b1e69d26d71bb5ee5579fa027cbc97a
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/4323911
Original-Commit-Queue: Yuval Peress <peress@google.com>
Original-Tested-by: Yuval Peress <peress@google.com>
Original-Reviewed-by: Yuval Peress <peress@google.com>
Original-Tested-by: CopyBot Service Account <copybot.service@gmail.com>
GitOrigin-RevId: 6e082683e7b6c8882c8d92cb7361fd94a942f9f1
Cr-Build-Id: 8693326771132667633
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693326771132667633
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: Ia3a9ca49484c4ca6e87b931f651aa3427145e13a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7406200
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>