ethernet/smsc911x: mark static to function smsc_enable_xmit()
When building with -fno-inline, the compiler complains about
undefined reference to this function. This happens when
building for code coverage. Since this function is only called
within the file, mark it static also.

Original-Signed-off-by: Daniel Leung <daniel.leung@intel.com>
GitOrigin-RevId: 3926710f645a667fd52b53cf742b5d5cb129b57d
Cr-Build-Id: 8694295748509651905
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8694295748509651905
Copybot-Job-Name: zephyr-project-main-copybot-downstream
Change-Id: I39023c071e73b8ca6dea16d5ff24a57e0409bcd6
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyrproject/+/7345976
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>